bitwarden/sdk-sm

crates/bitwarden/src/api/request/mod.rs
The Identity connect requests are hand written and seems to not contain the user agent.
=> Add UA to identity connect requests

.github/workflows/release-cli.yml
Add `bws` to tag and release name for the CLI, to distinguish it for the future with `bw` cli.
=> Change names for GitHub release in release CLI workflow

Cargo.lock, crates/bws/Cargo.toml
```
```
Remove the oldtime feature from chrono, which is bringing the time 0.1 crate and causing some dependabot alerts.
=> Remove the unused oldtime feature from chrono

crates/bws/src/main.rs, crates/bws/src/render.rs
```
```
Fixes #50. Also added support for NO_COLOR, which clap already respects, but we didn't.
=> Disable error coloring when specified by the user

crates/bws/src/main.rs
```
```
Switch the command order for the bws cli. Instead of `bws create secret`, move to a more logical `bws secret create` structure.
We have left the existing commands but have removed them from the help menu and marked them as deprecated.
- **main.rs:** Update command order
=> SM-815: Switch Command Order

Cargo.toml
```
```
I've done some performance analysis on the SDK, by using a test crate that creates a `bitwarden_json` client to login to an account with 7k items, doing a sync and decrypting all the ciphers. This is based on my state management PR so note that not all the sync data is decrypted which means these numbers aren't representative of what the final result is going to be once the SDK is complete.
| Operation           | Before                | After |
|-----------------|-------|-------|
| Debug - /sync    | 21s   | **1.5s** |
| Debug - decrypt | 500ms | **52ms**|
| Debug - binary size | 24 MB | **8.8 MB** |
| Debug - clean build | **25s** | 38s |
| Debug - incremental build | 0,8s | 0,8s |
| Operation           | Before                | After |
|-----------------|-------|-------|
| …
=> Enable some optimization flags

crates/bitwarden-json/src/response.rs
```
```
The error message `String` in `bitwarden-json` was passed as reference and then converted again into a `String`, by passing it directly we avoid a copy.
=> Remove unnecessary string copy

.github/workflows/lint.yml, crates/bitwarden-json/src/command.rs, crates/bitwarden-napi/src-ts/bitwarden_client/schemas.ts, languages/csharp/schemas.cs, languages/js_webassembly/bitwarden_client/schemas.ts, languages/python/BitwardenClient/schemas.py, support/schemas/bitwarden_json/Command.json
```
```
The recent folder reorganisation didn't change the links to the return types of the Command schema, this PR fixes this.
We can validate this in CI if we wanted by setting `#[deny(rustdoc::broken_intra_doc_links)]` and running `cargo doc --workspace --features internal`.
=> Fix invalid return types in schemas

.github/renovate.json
```
```
Configure renovate to not propose non-breaking changes of dependencies. To avoid always updating to the latest versions since Bitwarden will act as a library. (We will get the latest versions through the lockfile refresh)
=> Renovate: Disable non-breaking updates for rust

crates/bitwarden-json/Cargo.toml, crates/bitwarden-json/src/client.rs, crates/bitwarden-json/src/response.rs
```
```
`bitwarden_json` handles the errors from `Client` calls correctly and returns a JSON like `{success: false, errorMessage: "whatever"}`.
This is not the case if the command sent to the `run_command` is malformed, in this case it would just return the error as a String. I've changed this so the error returned is in the same JSON format as the `Client` calls.
`parse_settings` would also silently start using the defaults if the provided settings where malformed, I've printed an error message in that case, but it might be best to change the return type of `Client::new`, though this means updating all the language bindings as well.
=> Improve errors in bitwarden_json

crates/bitwarden/src/auth/api/request/mod.rs, crates/bitwarden/src/auth/api/response/identity_token_response.rs
```
```
Ensure any server error is handled properly in the SDK instead of silently ignored by converting it to an error using `reqwest` `error_for_status` fn.
Resolves #87 
A network error now resolves into 
```
Error:
0: HTTP status server error (504 Gateway Timeout) for url (https://localhost:8080/identity/connect/token)
```
=> [PM-2076] Properly handle error responses in send_identity_connect_request

crates/bitwarden-c/Cargo.toml, crates/bitwarden-json/Cargo.toml, crates/bitwarden-json/src/client.rs, crates/bitwarden-json/src/command.rs, crates/bitwarden-napi/Cargo.toml, crates/bitwarden-py/Cargo.toml, crates/bitwarden-wasm/Cargo.toml, crates/bitwarden/CHANGELOG.md, crates/bitwarden/Cargo.toml, crates/bitwarden/README.md, crates/bitwarden/src/client/auth_settings.rs, crates/bitwarden/src/client/client.rs, crates/bitwarden/src/client/mod.rs, crates/bitwarden/src/crypto.rs, crates/bitwarden/src/lib.rs, crates/bitwarden/src/mobile/client_crypto.rs, crates/bitwarden/src/mobile/client_kdf.rs, crates/bitwarden/src/mobile/crypto.rs, crates/bitwarden/src/mobile/kdf.rs, crates/bitwarden/src/mobile/mod.rs, crates/bws/Cargo.toml, package.json
```
```
Create a smaller client surface for the new mobile apps, by hiding all the secrets manager stuff under a `secrets` feature flag, and making a new encryption-focused API hidden under a `mobile` feature flag.
As an initial pass, I've implemented the KDF functions needed for login and the basics needed to initialise the cryptography parts of the client.
Sidenote: We really need to split the bitwarden_json::Command struct into multiple files 😨
=> [PM-3125] Initial setup on smaller mobile-only sdk

Cargo.lock, crates/bitwarden-json/src/client.rs, crates/bitwarden-json/src/command.rs, crates/bitwarden/Cargo.toml, crates/bitwarden/src/lib.rs, crates/bitwarden/src/mobile/mod.rs, crates/bitwarden/src/mobile/vault/client_folders.rs, crates/bitwarden/src/mobile/vault/client_vault.rs, crates/bitwarden/src/mobile/vault/folders/mod.rs, crates/bitwarden/src/mobile/vault/folders/request.rs, crates/bitwarden/src/mobile/vault/folders/response.rs, crates/bitwarden/src/mobile/vault/mod.rs, crates/bitwarden/src/vault/folder.rs, crates/bitwarden/src/vault/mod.rs
```
```
Implement folder models and folder decryption for the mobile SDK.
I've exposed the CipherString type directly in the schemas to avoid doing a lot of `.parse::<CipherString>()?` all over the place. It's defined inside the `mobile` module to limit the scope, as it's not something we want exposed in the normal SDK.
=> [PM-3131] Implement Folder decryption

crates/bitwarden-json/src/command.rs, crates/bitwarden/src/mobile/client_kdf.rs, crates/bitwarden/src/mobile/kdf.rs, crates/bitwarden/src/mobile/vault/client_folders.rs, crates/bitwarden/src/mobile/vault/client_vault.rs
```
```
The mobile API encryption/decryption clients never modify anything internally in the client, so the `&mut` references are unnecessary. Removing them will also help make using `uniffi` or putting the API client behind a `RwLock` for synchronization between threads more efficient.
=> Remove unnecessary mut from encryption/decryption clients

crates/bitwarden-napi/src/lib.rs, crates/bitwarden-py/src/lib.rs
```
```
Some `cfg`s were checking for a `target_arch` of `wasm`, this value is not valid, the only valid values are `wasm32` and `wasm64`.
You can check the possible values with this command:
```sh
rustc +nightly -Z unstable-options --print all-target-specs-json | jq '[ to_entries[] | { "target": .key, "arch": .value.arch, "target-family": .value."target-family" } | select(.arch | startswith("wasm")) ]'
```
=> Fix invalid target_arch

Cargo.lock, crates/bitwarden/Cargo.toml
```
```
The macro-generated code of `serde_repr` serialization implementation contains a lowercase struct, which generates a warning in rust-analyzer, seems like it doesn't show in CI, and it's not important, but I think it's a good idea to update the dependency to make the warning go away. 
https://github.com/dtolnay/serde-repr/releases/tag/0.1.16
=> Update serde_repr to fix some warnings

crates/bitwarden/src/client/client.rs, crates/bitwarden/src/mobile/vault/client_folders.rs, crates/bitwarden/src/secrets_manager/projects/create.rs, crates/bitwarden/src/secrets_manager/projects/get.rs, crates/bitwarden/src/secrets_manager/projects/list.rs, crates/bitwarden/src/secrets_manager/projects/update.rs, crates/bitwarden/src/secrets_manager/secrets/create.rs, crates/bitwarden/src/secrets_manager/secrets/get.rs, crates/bitwarden/src/secrets_manager/secrets/list.rs, crates/bitwarden/src/secrets_manager/secrets/update.rs
```
```
Every single use of it would immediately do `.as_ref().ok_or(Error::VaultLocked)?`, so make it just return the Result directly. This change originated in #70, but I'm opening a separate PR for it because it's been annoying me each time I implement something handling encryption or decryption lol
=> Make get_encryption_settings return Result

.github/workflows/build-cli.yml, .github/workflows/release-cli.yml, .gitignore, .prettierignore, about.hbs, about.toml
```
```
Add a `THIRDPARTY.html` release artifact with credits for dependencies.
Example is available in https://github.com/bitwarden/sdk/actions/runs/5682035579.
=> Generate thirdparty.html

crates/bitwarden-uniffi/src/lib.rs, crates/bitwarden-uniffi/src/vault/mod.rs
```
```
We missed adding this function to access the ClientVault from the uniffi API
=> Add missing client vault function

languages/swift/build.sh
```
```
We need to combine both modules modulemap files instead of replacing them
=> Fix iOS uniffi build by concatenating modulemaps correctly

crates/sdk-schemas/Cargo.toml
```
```
On the `sdk-schemas` crate we have some types behind an `internal` feature flag, which is not defined in `Cargo.toml`, this means that building with `--features internal` would enable those types behind the `internal` flag, but `--all-features` would not. This causes the `npm run schemas` command to not generate those types, because we're using `--all-features` in the `package.json` file.
By defining the features in the manifest file, we remove that inconsistency with `--all-features` and make sure that `npm run schemas` generates all the schemas correctly.
=> Explicitly define internal feature for sdk-schemas crate

crates/bitwarden-c/src/c.rs, crates/bitwarden-napi/src/client.rs
```
```
Fix panic when re-registering a logger. This should only happen if our logger got registered on a previous call, so there's no need to register it again.
Fixes #134, but it's also applicable to `bitwarden-c`
=> Fix panic when re-registering a logger

crates/sdk-schemas/src/main.rs
```
```
#180 accidentally added ProjectResponse twice when it should have added ProjectResponse and Project**s**Response
=> Fix typo in added schemas, ProjectsResponse was missing

crates/bitwarden/src/crypto/enc_string.rs, crates/bitwarden/src/error.rs
```
```
Rename CSParseError to EncStringParseError, to better match the new naming. No need to abbreviate, the name is short enough.
=> Rename EncString parse error

crates/bitwarden/Cargo.toml
```
```
Lock the generated `bitwarden-api-api` and `bitwarden-api-identity` to specific versions in `bitwarden` to avoid possible conflicts when new versions of these two are released.
CI is running cargo set-version to update the version numbers, and that seems to respect the `=` bound in my tests, so this seems safe to do.
=> Lock generated API crates to the specified version

.prettierignore, crates/bitwarden-uniffi/src/docs.rs, crates/bitwarden-uniffi/src/vault/mod.rs, crates/bitwarden-uniffi/src/vault/sends.rs, languages/kotlin/doc.md, support/docs/docs.ts
```
```
Add missing Sends API to the bitwarden-uniffi crate.
Also fixed copy-pasted comment in the password history function
=> Add Sends API in bitwarden-uniffi

.github/workflows/build-android.yml
```
```
An updated dependency results in errors in #194 . Bumping the rust version for the combine task in the android workflow which should resolve this.
=> Change gh action android combine rust toolchain to stable

crates/bitwarden/src/client/client_settings.rs, languages/csharp/BitwardenSdk.cs, languages/csharp/Program.cs, languages/csharp/bitwardenSdk.csproj, support/scripts/schemas.ts
```
```
Quicktype now supports System.Text.Json which we typically prefer over Newtonsoft when possible. I also changed settings to only require partial inputs.
=> Change to system.text for c#

languages/swift/Package.swift, languages/swift/build.sh
```
```
This fixes a few build warnings when integrating the Swift SDK package within an app:
> ld: warning: dylib (libbitwarden_uniffi.dylib) was built for newer iOS Simulator version (16.2) than being linked (15.0)
It looks like Rust probably uses the latest iOS deployment target/min iOS version if not specified. I added `IPHONEOS_DEPLOYMENT_TARGET="13.0"` to set this to iOS 13, which matches the version in Package.swift.
https://github.com/bitwarden/sdk/blob/c707fc9ff9a241b73ef7471f90a3d0b0e68c6e33/languages/swift/Package.swift#L9
> ld: warning: linking against a dylib which is not safe for use in application extensions: libbitwarden_uniffi.dylib
We need to link the SDK within an iOS app extension to use for auto fill. `RUSTFLAGS="-C link-arg=-Wl,-application_extension"` enables a …
=> Fix Swift build warnings

crates/bitwarden/src/vault/cipher/cipher.rs
```
```
Cipher notes are optional.
=> Change cipher notes to be optional

crates/bitwarden/src/client/client_settings.rs
```
```
Use the same urls for debug and release to avoid confusion.
=> Use the same urls for debug and release

languages/swift/build.sh
```
```
Running an iOS app linked against the SDK on a device results in a crash because the dynamic library can't be found.
> dyld[11647]: Library not loaded: libbitwarden_uniffi.dylib
In looking through the Apple docs, I found the following:
> Avoid using dynamic library files (.dylib files) for dynamic linking. An XCFramework can include dynamic library files, but only macOS supports these libraries for dynamic linking. Dynamic linking on iOS, watchOS, and tvOS requires the XCFramework to contain .framework bundles.
> For each library and each platform, build a binary static libary file (.a file) that includes slices for all the possible architectures the platform uses.
https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle#Avoid-issues-when-us …
=> Use static libs for the iOS Swift framework

crates/bitwarden/src/error.rs, crates/bitwarden/src/secrets_manager/projects/project_response.rs, crates/bitwarden/src/secrets_manager/secrets/secret_response.rs, crates/bitwarden/src/util.rs, crates/bws/src/render.rs
```
```
Secrets Manager objects are still using strings for date objects. Change to proper dates.
=> [SM-938] Change secrets manager to use proper dates

.github/workflows/build-android.yml, .github/workflows/delete-old-packages.yml, languages/kotlin/app/build.gradle, languages/kotlin/sdk/build.gradle
=> Change maven artifactId to sdk-android

crates/bitwarden/src/vault/cipher/cipher.rs, crates/bitwarden/src/vault/cipher/field.rs, crates/bitwarden/src/vault/cipher/login.rs, crates/bitwarden/src/vault/send.rs
```
```
Some of the fields in the encryption models were incorrectly marked as non-optional, when in reality null values can be valid. I've marked these as Optional instead
=> Fix encryption model optionals

crates/bitwarden/src/lib.rs
```
```
Fix new doc warning that started appearing, I assume because the new Rust update
https://github.com/bitwarden/sdk/actions/runs/6433340114/job/17470205155?pr=203
=> Fix new doc warning

.cargo/config.toml
```
```
Enable the ARMv8 Cryptographic Extensions, for a performance increase in our encryption operations (https://docs.rs/aes/latest/aes/#armv8-intrinsics-rust-161)
Enabling this requires using Rust 1.61, but I just realized that the changes in the `config.toml` would only apply to anyone building the SDK from source and not to anyone using it from crates.io. Seeing as we're using the latest stable when building ourselves, this seems okay.
=> Enable AES optimization in ARMv8

crates/bws/src/main.rs
Return a non-zero exit code when no subcommands are supplied. This matches the behavior in many other CLIs (`bw`, `git`, `ssh`, etc.).
- **`crates/bws/src/main.rs`:** Exit with a non-zero exit code
=> Return a non-zero exit code when no subcommands are supplied

crates/bitwarden/src/auth/login/access_token.rs, crates/bitwarden/src/auth/login/api_key.rs, crates/bitwarden/src/auth/login/password.rs
```
```
Switch from `from_str` to `parse` which requires one import less.
=> Switch from from_str to parse

Cargo.lock, crates/bitwarden/Cargo.toml, crates/bitwarden/src/auth/register.rs, crates/bitwarden/src/client/client.rs, crates/bitwarden/src/crypto/master_key.rs, crates/bitwarden/src/crypto/user_key.rs, crates/bitwarden/tests/register.rs
```
```
The `make_user_key` needs to use the same key as `decrypt_user_key`, which should be the stretched users key.
=> Fix make_user_key which previously didn't stretch the users key

crates/bitwarden/src/vault/cipher/cipher.rs
```
```
Implement individual vault item encryption and encryption. Note that at the moment it will not migrate items that don't have a key when encrypting.
=> [PM-4270] Individual cipher key encryption

.vscode/settings.json, crates/bitwarden/src/auth/jwt_token.rs, crates/bitwarden/src/auth/login/access_token.rs, crates/bitwarden/src/auth/login/api_key.rs, crates/bitwarden/src/auth/mod.rs, crates/bitwarden/src/util.rs
```
```
Move JWT handling from utils to auth. Also improve documentation and use `FromStr` instead of a custom function.
=> Extract JWT to it's own file

.github/workflows/delete-old-packages.yml
```
```
GitHub packages doesn't update the date on snapshots, this caused our cleanup script to cleanup a snapshot version in use.
=> Exclude snapshots from the GH artifact cleanup job

crates/bitwarden/src/crypto/aes_ops.rs, crates/bitwarden/src/crypto/mod.rs, crates/bitwarden/src/mobile/mod.rs, crates/bitwarden/src/mobile/vault/mod.rs, crates/bitwarden/src/secrets_manager/mod.rs, crates/bitwarden/src/tool/exporters/mod.rs, crates/bitwarden/src/tool/generators/mod.rs, crates/bitwarden/src/tool/mod.rs
```
```
All the functions in `Client` that return `Client*` were inside private modules, which make them accessible for use, but `cargo doc` will not document them. By making them public, the cargo docs generate the correct documentation.
Also made `aes_ops` private as it's not used outside the crypto module anymore.
=> Update public modules to get correct documentation

Cargo.lock, crates/bws/Cargo.toml, crates/bws/src/render.rs
Add an env output option to `bws`. This allows for easier command-line usage in scripts, particularly where a JSON or YAML parser is not desirable or available.
Basic usage examples in Bash:
- `source <(bws secret get ec9e0489-244e-4b3f-8782-b0a800fe562f -o env)`
- `bws secret list -o env > .env`
- **`crates/bws/src/render.rs`:** Output secrets in `key="value"` format
=> [BEEEP] SM-1005 - Add env output option

crates/bitwarden-uniffi/README.md, crates/bitwarden-uniffi/src/crypto.rs, crates/bitwarden-uniffi/src/docs.rs, crates/bitwarden-uniffi/src/lib.rs, crates/bitwarden/src/client/encryption_settings.rs, crates/bitwarden/src/mobile/client_crypto.rs, crates/bitwarden/src/mobile/crypto.rs, crates/bitwarden/tests/register.rs, languages/kotlin/app/src/main/java/com/bitwarden/myapplication/MainActivity.kt, languages/kotlin/doc.md, languages/swift/iOS/App/ContentView.swift
```
```
Split initializeCrypto into separate user and organization methods, so clients won't need to hold on to the master password until after sync is done to initialize the organization keys.
=> Split initializeCrypto

Cargo.lock, Cargo.toml, crates/bitwarden-uniffi/Cargo.toml, crates/bitwarden-uniffi/uniffi.toml, crates/bitwarden/Cargo.toml, crates/bitwarden/uniffi.toml, crates/uniffi-bindgen/Cargo.toml
```
```
Update the uniffi code generation to output immutable structs. I've pointed the dependencies to my fork until this is included in the main uniffi repo, but it should be enough to let the mobile devs test if the solution is appropiate for them.
=> Generate immutable records in uniffi bindings

crates/bitwarden/src/auth/api/request/mod.rs
```
```
Use reqwest constants instead of magic strings where possible.
Extracted from #44.
=> Use reqwest header constants

crates/bitwarden-c/Cargo.toml, crates/bitwarden-json/Cargo.toml, crates/bitwarden-napi/Cargo.toml, crates/bitwarden-py/Cargo.toml, crates/bitwarden-uniffi/Cargo.toml, crates/bitwarden-wasm/Cargo.toml, crates/bitwarden/Cargo.toml, crates/bw/Cargo.toml, crates/bws/Cargo.toml, crates/sdk-schemas/Cargo.toml
```
```
Sort `cargo.toml` files alphabetically.
=> Sort cargo.toml files

crates/bitwarden-api-api/Cargo.toml, crates/bitwarden-api-identity/Cargo.toml, crates/bitwarden/Cargo.toml
```
```
Ensures renovate treats them as `widen` which preserves the minimum version.
=> Change all dependencies to be ranges

.github/renovate.json, languages/csharp/global.json
```
```
Disable renovate from bumping the dotnet-sdk. We have prefer latest which should be sufficient.
=> Lock SDK to 6.0.100 and ignore with Renovate updates

Cargo.lock, crates/bitwarden-wasm/Cargo.toml
```
```
wasm-bindgen was pinned because version 0.2.88 had some accidental backwards incompatible breaking changes. Those are fixed in 0.2.89 so we can remove the pin now
=> Unpin wasm-bindgen

.github/workflows/build-dotnet.yml, .github/workflows/build-java.yml, .github/workflows/publish-php.yml, .github/workflows/publish-ruby.yml
```
```
With the recent addition of all the SDK language bindings, we've added a lot of CI jobs on PRs that are unnecessary and slow down builds. By switching them to run only on merge we should save some CI time.
Ultimately, we'd want some way to make it so that the `Build Rust Cross Platform` get only called once and reused for every language SDK, but for now this should help.
=> Reduce the number of CI jobs that are run on PRs

Cargo.lock, crates/bitwarden-uniffi/src/vault/mod.rs, crates/bitwarden/Cargo.toml, crates/bitwarden/src/mobile/vault/client_totp.rs, crates/bitwarden/src/vault/mod.rs, crates/bitwarden/src/vault/totp.rs
```
```
Convert the `TotpService` from `clients` repository to rust.
=> Initial TOTP implementation

crates/sdk-schemas/src/main.rs, support/scripts/schemas.ts
```
```
The `quicktype` schema generation seems to have trouble with types in schema files being referenced from other types in separate schema files, which created duplicate classes, with a lot of strange names.
Instead of generating one individual file for each response, we create a big struct with all the options. This seems to solve the issue of references between schema files, and so no duplicate classes are created.
Note that the way that the file is loaded in `quicktype` is different. By default, `quicktype` generates JSON conversion helper functions only for the root type, which would be the big struct `SchemaTypes`. By importing the file with `#/definitions/` appended, we only bring the sub schemas as root types, and ignore `SchemaTypes`, which we don't care about.
Examples of …
=> Generate better schema types

crates/bitwarden/src/auth/renew.rs, crates/bitwarden/src/client/client.rs
```
```
Refactor out the `Instant` type in Client and use unix timestamps. This is to support this PR: https://github.com/bitwarden/sdk/pull/388 where we need to serialize token expiry times.
It also brings benefits to other areas like WASM, where `Instant` doesn't exist.
- **crates/bitwarden/src/auth/renew.rs:** Update the `renew_token` function to use timestamps instead of the `Instant` type
- **crates/bitwarden/src/client/client.rs:** Update `Client` to store the unix timestamp for token expiration
=> SM-1023: Remove Instant from Client in SDK

crates/bitwarden-uniffi/src/auth/mod.rs, crates/bitwarden-uniffi/src/docs.rs, crates/bitwarden/src/auth/client_auth.rs, crates/bitwarden/src/auth/login/mod.rs, crates/bitwarden/src/auth/login/password.rs, crates/bitwarden/src/auth/login/two_factor.rs, crates/bitwarden/src/auth/mod.rs, crates/bitwarden/src/auth/password.rs, crates/bitwarden/src/crypto/master_key.rs, crates/bitwarden/src/crypto/mod.rs, crates/bitwarden/src/mobile/client_kdf.rs, crates/bitwarden/src/mobile/kdf.rs, languages/kotlin/doc.md
```
```
Client will call `hash_password` with `Purpose::Local`, persist it and revalidate by using `validate_password(password, persisted_hash)`.
Long term the SDK will persist the hash itself and not require it as input.
=> [PM-4930] Implement password validation

crates/bitwarden/src/auth/api/request/access_token_request.rs, crates/bitwarden/src/auth/login/access_token.rs, crates/bitwarden/src/auth/renew.rs, crates/bitwarden/src/client/access_token.rs, crates/bitwarden/src/client/client.rs, crates/bws/src/main.rs
```
```
Rename service_account_id to access_token_id to better represent the actual data. Since it's not a service account id but rather an access token id.
=> Rename service_account_id to access_token_id

languages/kotlin/app/src/main/java/com/bitwarden/myapplication/MainActivity.kt, languages/swift/iOS/App/ContentView.swift
```
```
Noticed the mobile demo apps weren't updated with the new hashPurpose parameter, also ran formatting over the files
=> Add missing hashPurpose to mobile demo apps

Cargo.lock, crates/bitwarden-uniffi/src/auth/mod.rs, crates/bitwarden-uniffi/src/crypto.rs, crates/bitwarden-uniffi/src/platform/mod.rs, crates/bitwarden-uniffi/src/tool/mod.rs, crates/bitwarden-uniffi/src/vault/ciphers.rs, crates/bitwarden-uniffi/src/vault/collections.rs, crates/bitwarden-uniffi/src/vault/folders.rs, crates/bitwarden-uniffi/src/vault/mod.rs, crates/bitwarden-uniffi/src/vault/password_history.rs, crates/bitwarden-uniffi/src/vault/sends.rs, crates/bitwarden/Cargo.toml
```
```
When testing the username generator using uniffi, I noticed that uniffi was using it's own async executor by default, while reqwest was expecting tokio, which caused errors. 
I've changed all uniffi exported async functions to use tokio by default, to avoid these issues.
=> Use tokio executor for uniffi async

crates/bitwarden-c/src/c.rs
```
```
Stop printing input string before each C API Call - it was leaking the accessTokenLogin
- **crates/bitwarden-c/src/c.rs:** Remove `println`
Before, GOLANG App using the "master" version of a built `libbitwarden_c.so`:
```
root@3109875c9808:/tmp# ./example 
{"accessTokenLogin":{"accessToken":"0.7a7e976d-dd5a-4915-8bbd-b0d50118903b.hmXzh9efndJxePmCgWs2neZq3lVFb1:87U3EjhGZq3ufZv+Mso5PA=="}}
{"projects":{"list":{"organizationId":"d2f88df6-b07b-4acb-9a0f-b09600cf89e5"}}}
{"secrets":{"list":{"organizationId":"d2f88df6-b07b-4acb-9a0f-b09600cf89e5"}}}
{"secrets":{"get":{"id":"697720c2-50f6-4dd9-8859-b0d501191ee5"}}}
{"secrets":{"get":{"id":"b6820a10-d6e3-490e-9476-b0d5012222d6"}}}
world2
```
After, same GOLANG App using my version of `libbitwarden_c.so` compiled without the `println`:
``` …
```
=> chore: stop printing input string before C commands

crates/bitwarden/src/auth/login/access_token.rs, crates/bitwarden/src/auth/login/api_key.rs, crates/bitwarden/src/auth/login/password.rs, crates/bitwarden/src/auth/renew.rs, crates/bitwarden/src/client/client.rs
```
```
There's no reason for these two to be combined, and it forces `renew_tokens` to clone login_method every time
=> Split set_login_method from set_tokens

crates/bitwarden/src/auth/login/access_token.rs, crates/bitwarden/src/auth/renew.rs, crates/bitwarden/src/client/access_token.rs, crates/bitwarden/src/client/client.rs
```
```
Now that set_login_method is split from set_tokens, we can just change this to directly contain the token without adding the Clone bound to it. This way we avoid duplicating 2/3rds of the AccessToken.
This should help with #388
=> Change login_method to have the access token directly

languages/ruby/bitwarden_sdk/lib/bitwarden-sdk.rb
```
```
Ruby emitted `null` in client settings which prevented rust from using the default implementation.
=> Tweak ruby to not emit null in settings

crates/bitwarden/src/client/encryption_settings.rs, crates/bitwarden/src/crypto/enc_string.rs
```
```
Organization keys can be generated using `Rsa2048_OaepSha1_HmacSha256_B64` which previously wasn't supported. This PR adds support for decrypting org keys in that format, and changes the part of asymetric hmac to also contain a mac.
=> Add support for Hmac org keys

crates/bitwarden/src/auth/jwt_token.rs, crates/bitwarden/src/auth/login/api_key.rs, crates/bitwarden/src/client/kdf.rs, crates/bitwarden/src/crypto/fingerprint.rs, crates/bitwarden/src/crypto/mod.rs, crates/bitwarden/src/crypto/rsa.rs, crates/bitwarden/src/error.rs, crates/bitwarden/src/platform/get_user_api_key.rs, crates/bitwarden/src/tool/generators/passphrase.rs, crates/bitwarden/src/tool/generators/password.rs, crates/bitwarden/src/uniffi_support.rs, crates/bitwarden/src/vault/totp.rs
```
```
Allow using dynamic strings on the Internal error variant, tested on the passphrase length error.
The Internal variant is using a `Cow<'static, str>`, to avoid unnecessary allocations on all the cases where a `&'static str` would suffice.
I've implemented `From<&'static str>` and `From<String>` for Error. It feels a bit magic, but it avoids repeating `Error::Internal` all over the place.
=> Improve internal error

crates/bitwarden/src/vault/cipher/attachment.rs
```
```
Change `AttachmentView` key to be an `EncString`, and skip decrypting it. This is to avoid a uniffi issue with the representation of Vec<u8> on Android.
Note that this is very similar to what we're doing with Sends, where we don't decrypt the key on the model either until we're ready to decrypt the file.
=> Change attachment key to EncString

crates/bitwarden/src/client/client.rs, crates/bitwarden/src/client/encryption_settings.rs, crates/bitwarden/src/crypto/enc_string/asymmetric.rs, crates/bitwarden/src/crypto/enc_string/mod.rs, crates/bitwarden/src/crypto/enc_string/symmetric.rs, crates/bitwarden/src/crypto/mod.rs, crates/bitwarden/src/error.rs, crates/bitwarden/src/mobile/crypto.rs, crates/bitwarden/src/uniffi_support.rs
```
```
Split `EncString` into an asymmetric variant. I've left the symmetric variant with the name `EncString` as it's the most common variant to avoid major changes.
This is somewhat related to #447 and should be merged first so that PR can take advantage of the symm/asymm separation.
I've moved the `EncString` files into their own folder to organize the crypto directory a bit better too.
=> Split EncString for asymmetric support

crates/bitwarden/src/vault/collection.rs, crates/bitwarden/src/vault/folder.rs, crates/bitwarden/src/vault/send.rs
```
```
Previously some of the model structs had non-optional IDs, this won't work when trying to encrypt a new item, as you won't have an ID until you POST it to the server.
This PR changes the id fields to be optional, matching what we already do on Cipher.
=> Make model IDs optional

crates/bitwarden-json/src/client.rs, crates/bitwarden-uniffi/src/platform/mod.rs, crates/bitwarden-uniffi/src/uniffi_support.rs, crates/bitwarden/src/client/client.rs, crates/bitwarden/src/client/encryption_settings.rs, crates/bitwarden/src/platform/client_platform.rs, crates/bitwarden/src/platform/generate_fingerprint.rs, crates/bitwarden/src/platform/mod.rs, languages/kotlin/doc.md
```
```
Add support for generating the users fingerprint using the private key from EncSettings.
=> Add support for generating the users fingerprint

crates/bitwarden/src/auth/jwt_token.rs
```
```
JWT should be url encoded and never use padding.
=> Change jwt parsing to use URL_SAFE_NO_PAD

crates/bitwarden/src/vault/totp.rs
```
```
Some totp providers use lowercase secrets. This isn't valid base32 though and needs to be transformed into uppercase prior to parsing.
=> Convert totp secret to uppercase

crates/bitwarden/src/crypto/mod.rs, crates/bitwarden/src/crypto/symmetric_crypto_key.rs, crates/bitwarden/src/vault/send.rs
```
```
When creating a new send, we should generate a key for it.
=> Support generating a random send key if none is provided

crates/bitwarden/src/vault/totp.rs
```
```
Fix difference in our totp handling in the sdk and clients repository.
=> Sanitize totp base32 and use no pad

crates/bitwarden/src/crypto/enc_string/symmetric.rs, crates/bitwarden/src/crypto/master_key.rs, crates/bitwarden/src/crypto/mod.rs, crates/bitwarden/src/crypto/symmetric_crypto_key.rs
```
```
The `MasterKey` previously had intimate knowledge about `SymmetricCryptKey` in order to be able to generate one. This refactor extracts the knowledge back into `SymmetricCryptoKey` by creating a `SymmetricCryptoKey::generate`.
=> Refactor make_user_key to call SymmetricCryptoKey::generate

crates/bitwarden-crypto/src/enc_string/asymmetric.rs, crates/bitwarden-crypto/src/enc_string/mod.rs, crates/bitwarden-crypto/src/lib.rs, crates/bitwarden/src/client/client.rs, crates/bitwarden/src/client/encryption_settings.rs, crates/bitwarden/src/mobile/crypto.rs, crates/bitwarden/src/uniffi_support.rs
```
```
Rename `AsymmEncString` to `AsymmetricEncString` to be consistent. We could consider renaming `AsymetricCryptoKey` to `AsymmCryptoKey` or some other variant if we prefer.
=> Rename AsymmEncString to AsymmetricEncString

.github/workflows/build-dotnet.yml, .github/workflows/build-java.yml, .github/workflows/publish-dotnet.yml, .github/workflows/publish-php.yml, .github/workflows/publish-ruby.yml, languages/csharp/Bitwarden.Sdk/Bitwarden.Sdk.csproj, languages/php/src/BitwardenLib.php, languages/ruby/bitwarden_sdk/bitwarden-sdk.gemspec, languages/ruby/bitwarden_sdk/lib/bitwarden_lib.rb
```
```
- Rename `ubuntu-x64` to `linux-x64` to better match the usage.
- Resolve java using the wrong prefixes. It should be `x86_64` for architecture, and windows should use `win32`.
Resolves #491 
=> Fix lib architectures in language SDKs

Cargo.lock, crates/bitwarden-uniffi/Cargo.toml, crates/bitwarden/src/tool/client_generator.rs, languages/kotlin/app/src/main/java/com/bitwarden/myapplication/MainActivity.kt, languages/swift/build.sh
```
```
It seems for uniffi to properly parse the uniffi.toml files it has to be a direct dependency and not transient like generators previously were.
=> Fix android not working properly

Cargo.lock, crates/bitwarden/Cargo.toml, crates/bitwarden/src/vault/totp.rs
```
```
Change base32 decoding for totp to use the same method as our other clients.
=> Swap out base32 decoding with custom implementation for totp

.github/workflows/build-android.yml, .github/workflows/build-cli.yml
```
```
The lockfile bump in #464 requires a newer rust version to build correctly. Unfortunately the latest released version of cross doesn't support newer rust versions for android To resolve this we target a newer revision.
=> Upgrade cross to a newer untagged release

Cargo.lock, crates/bitwarden-crypto/src/keys/device_key.rs, crates/bitwarden/Cargo.toml, crates/bitwarden/src/auth/auth_request.rs
```
```
Device keys are generated from random u8 vectors. We incorrectly attempted to parse these as strings when decrypting them in the last trust device step.
Added a complete test which confirms the whole device approval process.
=> Fix device keys incorrectly being treated as strings

crates/bitwarden-crypto/src/enc_string/asymmetric.rs, crates/bitwarden-crypto/src/enc_string/mod.rs, crates/bitwarden-crypto/src/enc_string/symmetric.rs
```
```
Extend unit testing for the crypto crate.
=> Write more tests for Crypto crate

crates/bitwarden/src/client/client.rs
```
```
We need to keep the version of rustls that reqwest and rustls-platform-verifier use in sync to avoid runtime errors when creating the reqwest client, we can't check it at compile time due to the use of `&dyn Any` and downcasting, but we can add a test.
=> Add test to ensure we are using a compatible rustls version

.github/workflows/build-cli-docker.yml, .github/workflows/release-cli.yml
```
```
Add docker publish to `release-cli.yml` workflow.
- **.github/workflows/release-cli.yml:** Add docker publish job to `release-cli.yml` workflow.
- **.github/workflows/build-cli-docker.yml** Remove unused input. Publish docker only if building for publish branch
=> [DEVOPS-1711] Add Docker image for bws versioning for release workflow

Cargo.lock, crates/bitwarden-c/src/c.rs, crates/bitwarden-c/src/macros/ffi.rs, crates/bitwarden-json/Cargo.toml, crates/bitwarden-json/src/client.rs, crates/bitwarden-napi/src/client.rs, crates/bitwarden-py/src/client.rs, crates/bitwarden-wasm/src/client.rs
```
```
I've added the lock into bitwarden-json because we already do locking in bitwarden-wasm and this way we can remove it from there.
=> [PM-6104] Add locking support to bitwarden-json to improve bindings thread safety

Cargo.lock, crates/bitwarden-crypto/src/keys/master_key.rs, crates/bitwarden-crypto/src/keys/mod.rs, crates/bitwarden-crypto/src/keys/pin_key.rs, crates/bitwarden-crypto/src/keys/utils.rs, crates/bitwarden-exporters/Cargo.toml, crates/bitwarden-exporters/src/encrypted_json.rs, crates/bitwarden-exporters/src/lib.rs, crates/bitwarden/src/tool/exporters/mod.rs
```
```
Implement encrypted export
=> [PM-3438] Encrypted export

Cargo.lock, crates/bitwarden-crypto/Cargo.toml, crates/bitwarden-crypto/src/encryptable.rs, crates/bitwarden-crypto/src/keys/key_encryptable.rs
```
```
Use rayon to multithread the encryption and decryption of ciphers. Note that this will have no benefit for  WASM, as in that case it falls back to a single thread model.
In my Mac I get 8-9x speedups when decrypting a big number of EncStrings.
=> [PM-6107] Use rayon to multithread encryption/decryption

crates/bitwarden-crypto/src/keys/device_key.rs, crates/bitwarden-crypto/src/uniffi_support.rs, crates/bitwarden-uniffi/src/auth/mod.rs, crates/bitwarden/src/auth/client_auth.rs, crates/bitwarden/src/mobile/crypto.rs, crates/bitwarden/src/uniffi_support.rs
```
```
Add Uniffi bindings for the TDE functionality.
=> [PM-6261] Add Uniffi bindings for TDE

crates/bitwarden-uniffi/src/lib.rs
```
```
We forgot to expose the ClientsExporters in the uniffi bindings.
=> Expose exporters for mobile

.github/workflows/version-bump.yml
```
```
- **.github/workflows/version-bump.yml:** Fix ruby sdk directory name in version bump workflow
=> [DEVOPS-1785] Fix ruby sdk directory in version bump workflow

.github/workflows/publish-ruby.yml
```
```
- **.github/workflows/publish-ruby.yml:** Add `contents: read` permission and fix indentation
=> [DEVOPS-1785] Fix publish ruby sdk workflow permissions

.github/workflows/publish-ruby.yml
```
```
- **.github/workflows/publish-ruby.yml:** Use `gem push` with rubygem API key instead of automated release steps.
=> [DEVOPS-1785] Change ruby publish workflow to use api key method

crates/bitwarden-uniffi/src/crypto.rs, crates/bitwarden/src/mobile/client_crypto.rs, crates/bitwarden/src/mobile/crypto.rs
```
```
Implement cryptographic logic for admin password reset.
=> [PM-6437] Implement admin password reset logic

.github/codecov.yml
```
```
Codecov says it merges global and local configs, but looks like it doesn't. Provides global status configuration so this doesn't fail checks.
* **.github/codecov.yml:** Checks configuration addition.
=> Provide global coverage configuration

crates/bitwarden-uniffi/src/auth/mod.rs, languages/kotlin/doc.md
```
```
Function was accidentally called `t` when it should have been called `trust_device`
=> Fix typo in `trust_device`

languages/go/example/example.go, languages/go/secrets.go
Allow secret fetching by a list of IDs, rather than requesting multiple secrets individually. Exposes the functionality from #150 in Go.
- **languages/go/secrets.go:** Add `GetByIDS` func.
- **languages/go/example/example.go:** Get secrets by ID. Added JSON output for QA/ease-of-use.
=> add get-by-ids to Go wrapper

.github/workflows/release-go.yml
```
```
- **.github/workflows/release-go.yml:** Use `bitwarden-devops-bot` PAT to checkout `sm-sdk-go` repo.
=> [DEVOPS-1750] Fix release Go SDK pipeline

.github/workflows/release-go.yml
```
```
- **.github/workflows/release-go.yml:** Fix files copy and repo name in create release
=> [DEVOPS-1750] Fix release go pipeline

crates/bws/Cargo.toml
```
```
Prevent unecessary files from being included in the crates distributed build.
=> Exclude unecessary files from published bws

.github/workflows/release-go.yml
```
```
Fix version reference in release artifacts in Go release workflow.
- **.github/workflows/release-go.yml:** Fix version reference in release artifacts
=> [DEVOPS-1750] Fix Go release artifacts

crates/bitwarden/CHANGELOG.md, crates/bitwarden/src/auth/access_token.rs, crates/bitwarden/src/auth/login/access_token.rs, crates/bitwarden/src/auth/mod.rs, crates/bitwarden/src/client/client.rs, crates/bitwarden/src/client/mod.rs, crates/bitwarden/src/secrets_manager/state.rs, crates/bws/src/main.rs
```
```
Move access token from client to auth.
=> Move access token to auth

crates/bitwarden/src/tool/exporters/mod.rs, crates/bitwarden/src/vault/cipher/cipher.rs, crates/bitwarden/src/vault/cipher/login.rs
```
```
Add `Fido2Credentials` to the `Login` struct to support storing passkeys. Currently we don't decrypt passkeys but rather pass them along encrypted to ensure we can re-encrypt the login without data loss.
=> [PM-6761] Add fido credentials to data model

crates/bitwarden-crypto/Cargo.toml, crates/bitwarden-generators/Cargo.toml, crates/bitwarden/Cargo.toml, crates/bitwarden/src/error.rs, crates/bitwarden/src/lib.rs
```
```
We accidentally exposed exporters and generators without feature flagging them. This PR properly puts them under the internal feature flag.
=> Mark exporters and generators as internal dependencies

.github/workflows/publish-php.yml, .github/workflows/version-bump.yml, languages/php/composer.json
```
```
Update release pipeline for PHP SDK.
=> [DEVOPS-1786] Update release pipeline for PHP SDK

.github/workflows/publish-dotnet.yml, .github/workflows/version-bump.yml, languages/csharp/Bitwarden.Sdk/Bitwarden.Sdk.csproj
```
```
- **.github/workflows/publish-dotnet.yml:** Inline publish dotnet workflow with Bitwarden publish workflows standards. 
- **.github/workflows/version-bump.yml** Add `dotnet-sdk` to version bump workflow.
- **languages/csharp/Bitwarden.Sdk/Bitwarden.Sdk.csproj** Add version and change name of the nuget.
=> [DEVOPS-1749] update release pipeline for C#

Cargo.lock, crates/bitwarden-api-api/Cargo.toml, crates/bitwarden-api-identity/Cargo.toml, crates/bitwarden-generators/Cargo.toml, crates/bitwarden/Cargo.toml
```
```
Previously rust-platform-verifier was pinned to an old version to keep it's rustls version the same as reqwest. The latest update to reqwest now contains a new rustls version which unblocks this update.
=> Update request and rust-platform-verifier

.github/workflows/release-go.yml
```
```
- **.github/workflows/release-go.yml:** Move `schemas.go` artifact to the `sm-sdk-go` repo root and repack zip artifacts to include only needed (`libbitwarden_c.*`) files.
=> [DEVOPS-1750] Change structure of sm-sdk-go repo

README.md, support/build-api.sh
```
```
Add a note about the required nightly toolchain. Without this people will receive an error when attempting to run the `build-api.sh` script.
For posterity, the nightly toolchain is required for certain features deemed unsafe. You can find more info here: https://github.com/bitwarden/sdk/pull/512
- **README.md:** Add nightly install instructions
=> Nightly Toolchain Note

crates/bitwarden-crypto/src/keys/master_key.rs, crates/bitwarden-crypto/src/rsa.rs, crates/bitwarden/src/auth/login/api_key.rs, crates/bitwarden/src/auth/login/auth_request.rs, crates/bitwarden/src/auth/login/password.rs, crates/bitwarden/src/mobile/vault/client_attachments.rs, crates/bitwarden/src/mobile/vault/client_sends.rs, crates/bitwarden/src/vault/cipher/login.rs, crates/bw/src/auth/login.rs
```
```
This PR replaces the unwraps found in the audit by proper error handling, I've also had a quick look through the rest of the code base and replaced a bunch of others as well.
=> [PM-7067] Remove unnecessary unwraps

crates/bitwarden-uniffi/src/auth/mod.rs, crates/bitwarden/src/auth/client_auth.rs, crates/bitwarden/src/auth/mod.rs, crates/bitwarden/src/auth/tde.rs, crates/bitwarden/src/client/client.rs
```
```
Add support in the SDK to create the keys necessary for the just in time user for TDE
=> [PM-7051] Implement make_register_tde_keys

crates/bitwarden-crypto/src/enc_string/symmetric.rs, crates/bitwarden-crypto/src/keys/device_key.rs, crates/bitwarden-crypto/src/keys/master_key.rs, crates/bitwarden-crypto/src/keys/mod.rs, crates/bitwarden-crypto/src/keys/shareable_key.rs, crates/bitwarden-crypto/src/keys/symmetric_crypto_key.rs, crates/bitwarden-crypto/src/lib.rs, crates/bitwarden-crypto/src/sensitive/decrypted.rs, crates/bitwarden-crypto/src/sensitive/mod.rs, crates/bitwarden-crypto/src/sensitive/sensitive.rs, crates/bitwarden-crypto/src/uniffi_support.rs, crates/bitwarden-uniffi/src/crypto.rs, crates/bitwarden-uniffi/src/uniffi_support.rs, crates/bitwarden/src/auth/access_token.rs, crates/bitwarden/src/auth/auth_request.rs, crates/bitwarden/src/auth/login/access_token.rs, crates/bitwarden/src/auth/renew.rs, crates/bitwarden/src/auth/tde.rs, crates/bitwarden/src/mobile/client_crypto.rs, crates/bitwarden/src/mobile/crypto.rs, crates/bitwarden/src/secrets_manager/state.rs, crates/bitwarden/src/uniffi_support.rs, crates/bitwarden/src/vault/cipher/attachment.rs, crates/bitwarden/src/vault/cipher/cipher.rs, crates/bitwarden/src/vault/send.rs, crates/memory-testing/src/bin/analyze-dumps.rs, crates/memory-testing/src/main.rs
```
```
This is a small subset of #536, which only contains the minimum code to protect the import/export functions on SymmetricCryptoKey. It also enables the from_base64 test on SymmetricCryptoKey as that passes now.
After this PR is merged I'll be expanding the use of Sensitive to other parts of the codebase while adding some extra memory testing checks to validate that it works for them.
=> Add sensitive types to SymmetricCryptoKey

.github/workflows/build-cli-docker.yml
```
```
- **.github/workflows/build-cli-docker.yml:** Push the docker image always and run build on PR, and branches push without specifying path of the change
=> Publish docker CLI to ACR from feature branches

crates/bws/Dockerfile
Addresses [PM-7068](https://bitwarden.atlassian.net/browse/PM-7068). Build the `bws` Docker image from an empty file system. This results in a much smaller Docker image (~16MB, uncompressed) with a smaller threat surface than bundling it with a distro.
- **./crates/bws/Dockerfile:** Use `scratch` for the final build stage. This results in a distroless image that only contains our binary, the libraries that it depends on, and the CA certificates needed for SSL to work. The `ldd` line automatically determines what dependencies we need to copy over so we don't have to manually maintain a list of them.
[PM-7068]: https://bitwarden.atlassian.net/browse/PM-7068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
=> [PM-7068] - Use a distroless container image for `bws`

.github/workflows/version-bump.yml, Cargo.lock, Cargo.toml, crates/bitwarden-api-api/Cargo.toml, crates/bitwarden-api-identity/Cargo.toml, crates/bitwarden-cli/Cargo.toml, crates/bitwarden-crypto/Cargo.toml, crates/bitwarden-exporters/Cargo.toml, crates/bitwarden-generators/Cargo.toml, crates/bitwarden-json/Cargo.toml, crates/bitwarden-napi/Cargo.toml, crates/bitwarden-py/Cargo.toml, crates/bitwarden-uniffi/Cargo.toml, crates/bitwarden-wasm/Cargo.toml, crates/bitwarden/Cargo.toml, crates/bw/Cargo.toml, crates/bws/Cargo.toml, crates/sdk-schemas/Cargo.toml
```
```
Rather than maintaining separate versions for every crate let's keep them locked. That means the rust sdk packages will always have the same version. Unfortunately a side effect of this is that every package will be released even if that package hasn't changed.
=> Use same version for bitwarden crates

Cargo.lock, crates/bitwarden-uniffi/Cargo.toml, crates/bitwarden-uniffi/src/uniffi_support.rs, crates/bitwarden-uniffi/src/vault/ciphers.rs, crates/bitwarden/src/mobile/vault/client_ciphers.rs, crates/bitwarden/src/vault/cipher/cipher.rs, languages/kotlin/doc.md
```
```
Added function to allow moving a cipher to an organization, which requires reencrypting the cipher key if it has one.
=> [PM-6764] Move cipher to organization

languages/kotlin/sdk/build.gradle
```
```
Since we share the same version across crates we need to load it from the root `cargo.Toml` instead of `crates/bitwarden/cargo.Toml`. Resolves the Android SDK no longer building.
=> Fix android build errors

crates/bitwarden-py/src/client.rs
When running the `ansible-playbook` command, we needed to export the following variable: `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`. This suppresses fork safety warnings on Mac OS. With this set, you can safely query for individual secrets. However, if you query for secrets within an Ansible loop or with a Jinja2 template, we receive an error that is caused by setting up a logger more than once. (This error comes from the `pyo3_log` crate.)
If we switch to using the `pyo3_log::try_init` function, we ignore the case where a logger is already set up if the attempt fails. This happens because the `pyo3_log::init` function [can panic](https://github.com/vorner/pyo3-log/blob/70819388bfcb58a7ca91a27179a73cea0abde31e/src/lib.rs#L569). This also introduces panic safety.
- **client.rs:** …
=> SM-1147: Switch to try_init with pyo3_log

crates/bitwarden-generators/src/username_forwarders/fastmail.rs
```
```
It seems the web clients use `forDomain` instead of `url` for website. This changes the SDK to send the same values.
=> Change fastMail to use forDomain instead of url

Cargo.lock, crates/bitwarden-api-api/Cargo.toml, crates/bitwarden-api-identity/Cargo.toml, crates/bitwarden-generators/Cargo.toml, crates/bitwarden/Cargo.toml, support/openapi-template/Cargo.mustache
```
```
Some websites will require `http2` support and we should have that feature enabled to avoid errors.
=> Enable http2 feature for reqwest

crates/bitwarden-crypto/src/keys/master_key.rs, crates/bitwarden-crypto/src/keys/mod.rs, crates/bitwarden-uniffi/src/auth/mod.rs, crates/bitwarden/src/auth/api/response/identity_success_response.rs, crates/bitwarden/src/auth/client_auth.rs, crates/bitwarden/src/auth/login/auth_request.rs, crates/bitwarden/src/auth/login/mod.rs, crates/bitwarden/src/auth/register.rs, crates/bitwarden/src/auth/tde.rs, crates/bitwarden/src/util.rs
```
```
We should set login_method when registering TDE keys
=> Set login_method when registering for tde

.github/workflows/publish-php.yml
```
```
This PR pins the `bitwarden/gh-actions/get-keyvault-secrets` actions to `main`.
- **.github/workflows/publish-php.yml:** Pin all uses of `bitwarden/gh-actions/get-keyvault-secrets` to `main`.
=> DEVOPS-1939 - Pin actions to main

.github/workflows/build-wasm.yml
```
```
We have a desire to publish every build of the wasm to gh package for faster use in the clients repository.
=> [PM-7447] Publish prerelease to GitHub packages

bacon.toml
```
```
Adds a bacon config which is useful when writing rustdoc. `bacon doc-internal-open` will re-build the doc on changes.
=> Add bacon config

bacon.toml, crates/bitwarden-crypto/src/keys/master_key.rs, crates/bitwarden-crypto/src/lib.rs, crates/bitwarden-crypto/src/rsa.rs, crates/bitwarden-crypto/src/wordlist.rs, crates/bitwarden-exporters/src/csv.rs, crates/bitwarden-generators/src/username.rs, crates/bitwarden/src/client/client.rs, crates/bitwarden/src/mobile/crypto.rs
```
```
Add some more documentation for crypto crate.
=> Add more docs to crypto crate

README.md, crates/bitwarden-napi/Cargo.toml
```
```
Documented the tools we use for development. Sadly couldn't integrate `nextest` into `bacon` as the output is too different and `bacon` relies on parsing it to work. I still included it in the list for the cases where devs run it manually.
I've also removed the `lto = true` instruction from bitwarden-napi, as it was ignored in favor of the workspace setting and was producing a warning.
=> Document developer tools

.vscode/settings.json, crates/bitwarden-crypto/src/keys/shareable_key.rs, crates/bitwarden-crypto/src/keys/symmetric_crypto_key.rs, crates/bitwarden-crypto/src/sensitive/sensitive.rs, crates/bitwarden-crypto/src/util.rs, crates/bitwarden-exporters/src/encrypted_json.rs, crates/bitwarden/src/auth/access_token.rs, crates/bitwarden/src/vault/send.rs
```
```
Make `generate_random_bytes` return `Sensitive`. Also migrate `derive_shareable_key` to accept a sensitive input.
=> Mark generate_random_bytes to return sensitive

Cargo.lock, crates/bitwarden-crypto/src/keys/master_key.rs, crates/bitwarden-crypto/src/sensitive/sensitive.rs, crates/bitwarden-json/src/client.rs, crates/bitwarden-uniffi/src/auth/mod.rs, crates/bitwarden-uniffi/src/crypto.rs, crates/bitwarden-wasm/Cargo.toml, crates/bitwarden-wasm/src/client.rs, crates/bitwarden/src/auth/auth_request.rs, crates/bitwarden/src/auth/client_auth.rs, crates/bitwarden/src/auth/login/api_key.rs, crates/bitwarden/src/auth/login/password.rs, crates/bitwarden/src/auth/login/two_factor.rs, crates/bitwarden/src/auth/mod.rs, crates/bitwarden/src/auth/password/validate.rs, crates/bitwarden/src/auth/register.rs, crates/bitwarden/src/client/client.rs, crates/bitwarden/src/mobile/client_crypto.rs, crates/bitwarden/src/mobile/client_kdf.rs, crates/bitwarden/src/mobile/crypto.rs, crates/bitwarden/src/mobile/kdf.rs, crates/bitwarden/src/platform/generate_fingerprint.rs, crates/bitwarden/src/platform/get_user_api_key.rs, crates/bitwarden/src/platform/secret_verification_request.rs, crates/bitwarden/src/vault/send.rs, crates/bitwarden/tests/register.rs, crates/bw/Cargo.toml, crates/bw/src/auth/login.rs, crates/bw/src/main.rs
```
```
Use Sensitive in MasterKey and bubble up the Sensitive change for all the requests that contain a password or pin. Note that this requires changing the request structs to be taken by value.
=> [PM-7066] Use Sensitive in MasterKey

crates/bitwarden/CHANGELOG.md
=> [SM-1189] Update change log with fix

crates/bitwarden/src/client/client.rs
```
```
Just discovered that `Option::insert` is a thing, which simplifies some code that first sets the value and then immediately returns a reference to it.
=> Use Option::insert()

languages/ruby/README.md
```
```
Update README for Ruby language local development. 
=> Update development section in ruby readme

crates/bitwarden/Cargo.toml
```
```
Remove wildcard dep that forbids publishing to crates.io. Set the version to the same one used everywhere else.
=> Remove reqwest wildcard dependency

crates/bitwarden-crypto/src/keys/master_key.rs, crates/bitwarden-crypto/src/keys/pin_key.rs, crates/bitwarden-crypto/src/keys/symmetric_crypto_key.rs, crates/bitwarden-crypto/src/keys/utils.rs, crates/bitwarden-crypto/src/sensitive/sensitive.rs, crates/bitwarden-crypto/src/util.rs, crates/bitwarden-exporters/src/encrypted_json.rs, crates/bitwarden-exporters/src/lib.rs, crates/bitwarden-uniffi/src/auth/mod.rs, crates/bitwarden/src/auth/client_auth.rs, crates/bitwarden/src/auth/login/password.rs, crates/bitwarden/src/auth/login/two_factor.rs, crates/bitwarden/src/auth/mod.rs, crates/bitwarden/src/auth/password/validate.rs, crates/bitwarden/src/auth/register.rs, crates/bitwarden/src/mobile/client_kdf.rs, crates/bitwarden/src/mobile/crypto.rs, crates/bitwarden/src/mobile/kdf.rs, crates/bitwarden/src/platform/get_user_api_key.rs, crates/bitwarden/src/tool/exporters/mod.rs, crates/bitwarden/src/vault/send.rs, crates/memory-testing/Dockerfile, crates/memory-testing/cases.json, crates/memory-testing/run_test.sh, crates/memory-testing/src/bin/analyze-dumps.rs, crates/memory-testing/src/bin/capture-dumps.rs, crates/memory-testing/src/lib.rs, crates/memory-testing/src/main.rs
```
```
- The `pbkdf2` and `argon` implementation have been updated to use their `SensitiveVec`s as buffers and outputs. 
- Some functions are using `inline(always)` to avoid stack copies.
- The `base64` implementation was updated to avoid using `decode_string` as that produced some leaks in some circumstances, instead we decode to a `SensitiveVec` and then use `try_into` to convert to a `String`.
- The testing framework has been expanded with some MasterKey cases, and the Dockerfile has been improved to cache the built dependencies, allowing a much faster develop-test loop.
Note that some of the argon tests are leaky for the moment, I've tested the new pre-release versions of the crypto crates, which include new zeroize features for sha1, sha2, and blake2 (used by argon). This seems to …
=> Improve memory security around KDF and MasterKey::derive

crates/bitwarden-crypto/src/uniffi_support.rs
```
```
We're using SensitiveString type in the API now, so this workaround is not necessary anymore
=> [PM-7214] Remove uniffi workaround

crates/bitwarden-crypto/src/enc_string/asymmetric.rs, crates/bitwarden-crypto/src/enc_string/symmetric.rs, crates/bitwarden-crypto/src/keys/asymmetric_crypto_key.rs, crates/bitwarden-crypto/src/keys/device_key.rs, crates/bitwarden-crypto/src/keys/master_key.rs, crates/bitwarden-crypto/src/keys/shareable_key.rs, crates/bitwarden-crypto/src/lib.rs, crates/bitwarden-crypto/src/sensitive/sensitive.rs, crates/bitwarden/src/auth/access_token.rs, crates/bitwarden/src/auth/auth_request.rs, crates/bitwarden/src/auth/mod.rs, crates/bitwarden/src/auth/password/validate.rs, crates/bitwarden/src/auth/tde.rs, crates/bitwarden/src/mobile/crypto.rs, crates/bitwarden/src/tool/exporters/mod.rs, crates/bitwarden/src/vault/cipher/attachment.rs, crates/bitwarden/src/vault/cipher/cipher.rs, crates/bitwarden/src/vault/cipher/login.rs, crates/bitwarden/src/vault/send.rs
```
```
With this, we can remove all the uses of .`expose()` from tests, which makes it much easier to see possible areas of improvement for Sensitive coverage.
With this PR we can compare the following:
- `Sensitive<V>` == `Sensitive<V>`
- `Sensitive<V>` == `V`
- `Sensitive<String>` == `&str`
- `Sensitive<Vec<u8>>` == `&[u8]`
I tried to replace the last two with a generic impl that would just take AsRef<> instead, but couldn't do it without conflicting implementations.
Note that the position is important, for example `V` == `Sensitive<V>` will not compile, and I don't think we can implement a blanket `Eq` for a generic `V` without running afoul of the orphan rules.
=> Implement Eq and PartialEq for Sensitive and their inner types

crates/bitwarden-crypto/src/fingerprint.rs
```
```
In `fingerprint`, we were calculating the SHA256 hash and ignoring the result, to then proceed and calculate the `Hkdf<Sha256>`.
This PR removes the unnecessary hash.
=> Remove unused hash from fingerprint

Cargo.lock, crates/bitwarden-crypto/Cargo.toml, crates/bitwarden-generators/Cargo.toml, crates/bitwarden-uniffi/Cargo.toml, crates/bitwarden/Cargo.toml, crates/uniffi-bindgen/Cargo.toml, languages/java/gradle/wrapper/gradle-wrapper.properties, languages/kotlin/app/build.gradle, languages/kotlin/build.gradle, languages/kotlin/gradle/wrapper/gradle-wrapper.properties, languages/kotlin/sdk/build.gradle
```
```
Update uniffi crates to get async traits support for the passkeys API
This update doesn't have any breaking code changes but it requires updating the Android compile SDK to 34, which also means updating the Android Gradle Plugin and the Gradle Wrapper version. Personally, I also had to update Android Studio to the latest version for it to work. Presumably this won't matter to SDK users, as they will use the compiled artifact directly.
While I was at it I also decided to update and cleanup the sdk-android package dependencies.
I also updated the gradle wrapper version for the Java secrets-manager bindings to keep them in sync, though this is not needed.
=> Update uniffi to 0.27.x for async traits support

crates/bitwarden-crypto/src/sensitive/sensitive.rs, crates/bitwarden-uniffi/src/auth/mod.rs, crates/bitwarden/src/auth/client_auth.rs, crates/bitwarden/src/auth/password/policy.rs, crates/bitwarden/src/auth/password/strength.rs
```
```
Add sensitive to password strength and password policy. This required adding some ways to get the length of a Sensitive String and check if all the characters match a predicate. 
The is_empty added to SensitiveString is because there's a lint for `len` implementation without a corresponding `is_empty`.
=> Add sensitive to password strength and password policy

Cargo.lock, crates/memory-testing/Cargo.toml, crates/memory-testing/Dockerfile, crates/memory-testing/cases.json, crates/memory-testing/run_test.sh, crates/memory-testing/src/bin/analyze-dumps.rs, crates/memory-testing/src/bin/capture-dumps.rs, crates/memory-testing/src/lib.rs, crates/memory-testing/src/main.rs
```
```
Improve how the memory-testing crate does some things:
- Compile and run the process in release mode, to better match what our final artifacts will do.
- Improve the structure of `Cases` struct, now the values that we want to look up in memory are generic, which greatly simplifies the `analyze-dumps` binary.
- Removed the test string from the table output, if we don't find the test string in the dump we assume the dump is invalid and return directly.
- Instead of waiting a predefined amount of time, the dump program now waits for the program to notify that it's ready, which speeds up the operations a bit.
- Use `black_box` instead of just printing the values, to ensure the compiler doesn't optimize them out.
=> Improve memory testing

crates/bitwarden-crypto/Cargo.toml, crates/bitwarden-crypto/src/sensitive/sensitive.rs, crates/bitwarden-exporters/Cargo.toml, crates/bitwarden/Cargo.toml
```
```
Hide `Sensitive::test` behind a feature flag which is only added as a dev-dependency.
=> Hide Sensitive::test behind flag

crates/bitwarden-exporters/src/lib.rs
```
```
Latest Rust 1.78 includes a [clippy warning](https://rust-lang.github.io/rust-clippy/master/index.html#/to_string_trait_impl) when implementing ToString directly instead of using Display, which would also derive `ToString` for free. Note that there are a few uses of `impl ToString` in the `bitwarden-api-*` packages but I haven't changed those here. I've opened a PR in openapi-generator https://github.com/OpenAPITools/openapi-generator/pull/18633
=> Use Display impl instead of ToString

crates/bitwarden-generators/src/passphrase.rs
```
```
This was breaking due to some changes to the formatter in nightly that were formatting a comment that was previously fine: https://github.com/bitwarden/sdk/actions/runs/9059887702/job/24888426878
To avoid it being split over three lines, I just moved it above the line
=> Edit comment to fix new nightly builds

.github/workflows/build-rust-cross-platform.yml
[SM-1236](https://bitwarden.atlassian.net/browse/SM-1236)
Add the following targets to the build workflow:
- x86_64-pc-windows-gnu
- x86_64-unknown-linux-musl
- aarch64-unknown-linux-musl
These are needed to produced statically-linked binaries with our Go language wrapper.
- Cross-compile the MUSL targets with Zig and add the Windows GNU target. 
- Adjusted the workflow to _just_ build the `bitwarden-c` crate. Previously, it was building every crate in the workspace.
[SM-1236]: https://bitwarden.atlassian.net/browse/SM-1236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SM-1236] - Add new targets for Go wrapper

Cargo.lock, crates/bitwarden-crypto/Cargo.toml, crates/bitwarden-generators/Cargo.toml, crates/bitwarden-uniffi/Cargo.toml, crates/bitwarden-uniffi/src/lib.rs, crates/bitwarden/Cargo.toml, crates/uniffi-bindgen/Cargo.toml
```
```
Update Uniffi to 0.29.2 to solve a memory leak in RustBuffer, and also add a logging implementation for the mobile clients.
Note that `env_logger` doesn't work for Android so it needs a `Logcat` specific logger. (Thankfully this one [doesn't panic](https://docs.rs/android_logger/latest/android_logger/fn.init_once.html) when called repeatedly)
=> Update uniffi and add logging support

crates/memory-testing/cases.json, crates/memory-testing/src/lib.rs, crates/memory-testing/src/main.rs
```
```
Add memory testing for `AsymmetricCryptoKey`
=> Add memory testing for asymmetric crypto keys

crates/bitwarden/CHANGELOG.md, crates/bitwarden/src/client/mod.rs, crates/bitwarden/src/lib.rs
It's a bit cumbersome to import `ClientSettings` and `DeviceType` from `client::client_settings` namespace. We can expose it in the root directly.
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more …
=> Export ClientSettings and DeviceType in the root namespace

crates/bitwarden/CHANGELOG.md, crates/bitwarden/src/client/client.rs
Remove deprecated `access_token_login`. We want to do this before releasing a stable SDK for secrets manager.
team …
=> Remove deprecated access_token_login

crates/bitwarden-uniffi/src/docs.rs, crates/bitwarden-uniffi/src/lib.rs, crates/bitwarden-uniffi/src/tool/mod.rs, crates/bitwarden-uniffi/src/tool/sends.rs, crates/bitwarden-uniffi/src/vault/mod.rs, crates/bitwarden/src/mobile/mod.rs, crates/bitwarden/src/mobile/tool/client_sends.rs, crates/bitwarden/src/mobile/tool/mod.rs, crates/bitwarden/src/mobile/vault/mod.rs, crates/bitwarden/src/tool/mod.rs, crates/bitwarden/src/tool/send.rs, crates/bitwarden/src/vault/mod.rs, crates/bitwarden/src/vault/sync.rs
The Sends feature is currently owned by the tools team, however in the SDK it's under Vault. Refactoring the code and extracting Sends as a top level client, and moving the code to the appropriate folder.
team …
=> Move sends to tools

README.md, crates/bitwarden/src/auth/mod.rs, crates/bitwarden/src/client/mod.rs, crates/bitwarden/src/client/test_accounts.rs, crates/bitwarden/src/mobile/vault/client_ciphers.rs, crates/bitwarden/src/mobile/vault/client_collection.rs, crates/bitwarden/src/tool/send.rs, crates/bitwarden/src/vault/collection.rs, crates/bitwarden/src/vault/folder.rs, crates/bitwarden/src/vault/password_history.rs
In #738 we migrated away from `decrypt` and used `decrypt_with_key` instead. However ciphers can be encrypted using either organization keys or user key. The changes introduced meant we always used the users key instead of conditionally based on the value of `organization_jd` in `Cipher`.
The fix was to call `locate_key` on `Cipher` and `Collection`.
To properly write tests I needed to mock a user account and organization. I took this moment to refactor our tests account and we now have nice helpers for initializing the test@bitwarden.com account, which also includes an organization.
- Protected functional changes with optionality (feature …
=> Fix ciphers & collections using wrong key when decrypting

.github/renovate.json
https://bitwarden.atlassian.net/browse/SM-1288
Configure dependency tracking for the Go wrapper. Dependency upgrades should be tracked here, rather than the `bitwarden/sm-sdk-go` repo, since this is the source for what gets pushed there.
team …
=> [SM-1288] - Configure renovate to track go dependencies

Cargo.lock, crates/bitwarden/Cargo.toml
I'm having compile errors running the iOS build, caused by the latest version of the `security-framework` crate including some MacOS symbols into the iOS binary.
The bug is [fixed upstream](https://github.com/kornelski/rust-security-framework/pull/204) but there haven't been any releases since then, so for now the best course of action is to pin the crate to the previous working version.
- Updated any necessary documentation (Confluence, contributing …
=> Pin security-framework to fix iOS build issues

crates/bitwarden/src/client/test_accounts.rs, crates/bitwarden/src/mobile/vault/client_ciphers.rs, crates/bitwarden/src/vault/cipher/attachment.rs, crates/bitwarden/src/vault/cipher/cipher.rs
- Added support for decrypting attachments without keys, for backwards compatibility
- Updated `move_to_organization` and `generate_cipher_key` to reencrypt attachment keys when possible or error out when it's not.
- Fix `generate_cipher_key` incorrectly encrypting the new cipher key with the old cipher key when the cipher already had a key.
team
- 👍 …
=> [PM-8657] Handle attachments with cipher keys

crates/bitwarden/src/platform/fido2/authenticator.rs, crates/bitwarden/src/vault/cipher/cipher.rs, crates/bitwarden/src/vault/cipher/login.rs, crates/bitwarden/src/vault/cipher/mod.rs
We don't need to expose the `Fido2CredentialView` for ciphers since the data isn't used by the UI. Instead we can expose the encrypted view and ensure it is re-encrypted on move.
team …
=> Use Fido2Credential instead of view in CipherView

crates/bws/Dockerfile
After the `bws` Docker image got moved to use `scratch` as a base image, non-root support got removed. This PR introduces it again, which should also remedy the SonarCloud scanner CI failure.
team
- 🤔 …
=> Use non-root in bws scratch Docker image

crates/bitwarden-crypto/src/keys/utils.rs, crates/memory-testing/cases.json
The argon2 library doesn't seem to clear the stack after doing a hash, but we can overwrite the stack by calling a function that creates a big stack allocated array right after the hash operation.
I've tried changing the parameters to the argon2 function and tweaking the array size to see where the limit should be, and in most of my tests clearing around 3700 bytes is enough. I've decided to round it up to the page size to be safe.
- Updated any …
=> Clear stack after argon2

crates/bitwarden/src/platform/fido2/authenticator.rs
The current call to `get_selected_credential` inside `save_credential` will try to fetch and decrypt the ciphers FIDO2 credentials, and error if they are not there. 
This can only happen when creating a new Passkey, so instead of calling `get_selected_credential` we just get the value from the lock. The other places where `get_selected_credential` is used is in `update_credential` and right at the end of the `assertion`, `register` and `authenticate` operations, so those should be safe.
- Communicated to …
=> Fix save_credential failing when the selected cipher doesn't have a Passkey

crates/bitwarden/src/platform/fido2/authenticator.rs, crates/bitwarden/src/platform/fido2/mod.rs
`selected_credential` is a misleading name as the selected value doesn't have to contain credentials, for example when creating a new passkey a cipher will usually not contain any credentials. Renaming it to `selected_cipher` should help clear the confusion a bit.
I've left the `get_selected_credential` function with the same name, as in this case we are actually getting the credential inside the cipher.
- Updated any necessary documentation …
=> Rename selected_credential to selected_cipher

Cargo.lock, crates/bitwarden-exporters/Cargo.toml, crates/bitwarden-exporters/src/lib.rs, crates/bitwarden-exporters/src/models.rs, crates/bitwarden-vault/Cargo.toml, crates/bitwarden-vault/src/cipher/field.rs, crates/bitwarden-vault/src/cipher/mod.rs, crates/bitwarden-vault/src/cipher/secure_note.rs, crates/bitwarden-vault/src/lib.rs
In preparation for #798 we need to flip the relationship between vault and exporters. Due to exporters in the future getting a `client_exporters` which means they need to be able to access the vault models to properly model it.
team
- ❓ …
=> Flip the dependency between exporters and vault

crates/bitwarden-vault/src/cipher/linked_id.rs
Clippy was complaining in my local build that this into was unnecessary, and for some reason this wasn't caught by CI
team …
=> Remove unnecessary into()

Cargo.toml, crates/bitwarden-uniffi/src/auth/mod.rs, crates/bitwarden-uniffi/src/crypto.rs, crates/bitwarden-uniffi/src/tool/mod.rs, crates/bitwarden-uniffi/src/tool/sends.rs, crates/bitwarden-uniffi/src/vault/attachments.rs, crates/bitwarden-uniffi/src/vault/ciphers.rs, crates/bitwarden-uniffi/src/vault/collections.rs, crates/bitwarden-uniffi/src/vault/folders.rs, crates/bitwarden-uniffi/src/vault/password_history.rs, crates/bitwarden/src/auth/client_auth.rs, crates/bitwarden/src/mobile/client_crypto.rs, crates/bitwarden/src/mobile/tool/client_sends.rs, crates/bitwarden/src/mobile/vault/client_attachments.rs, crates/bitwarden/src/mobile/vault/client_ciphers.rs, crates/bitwarden/src/mobile/vault/client_collection.rs, crates/bitwarden/src/mobile/vault/client_folders.rs, crates/bitwarden/src/mobile/vault/client_password_history.rs, crates/bitwarden/src/tool/client_generator.rs, crates/bitwarden/src/tool/exporters/client_exporter.rs, crates/bw/src/main.rs
We currently use async on several methods that don't actually require it. This PR enables the clippy rule which will warn if any async is unnecessary. It also resolves all existing usages.
team
- 🤔 …
=> Deny unused async

crates/bitwarden-uniffi/src/platform/fido2.rs, crates/bitwarden/src/client/client.rs, crates/bitwarden/src/error.rs, crates/bitwarden/src/platform/fido2/authenticator.rs, crates/bitwarden/src/platform/fido2/client.rs, crates/bitwarden/src/platform/fido2/crypto.rs, crates/bitwarden/src/platform/fido2/mod.rs, crates/bitwarden/src/platform/fido2/traits.rs, crates/bitwarden/src/platform/fido2/types.rs
This PR establishes explicit error types for the fido logic.
In order to extract the fido logic into a separate `bitwarden-fido` crate, we need to remove the dependencies on the `bitwarden` logic. Most of this is either the `Client` struct which is currently difficult, or the `Error` and `Result` types which this PR focuses on.
team
- 👍 (`:+1:`) or …
=> Migrate fido logic to use explicit errors

Cargo.lock, crates/bitwarden-json/Cargo.toml, crates/bitwarden-json/src/client.rs, crates/bitwarden-uniffi/Cargo.toml, crates/bitwarden/src/auth/client_auth.rs, crates/bitwarden/src/secrets_manager/client_projects.rs, crates/bitwarden/src/secrets_manager/client_secrets.rs, crates/bitwarden/src/secrets_manager/projects/create.rs, crates/bitwarden/src/secrets_manager/projects/delete.rs, crates/bitwarden/src/secrets_manager/projects/get.rs, crates/bitwarden/src/secrets_manager/projects/list.rs, crates/bitwarden/src/secrets_manager/projects/update.rs, crates/bitwarden/src/secrets_manager/secrets/create.rs, crates/bitwarden/src/secrets_manager/secrets/delete.rs, crates/bitwarden/src/secrets_manager/secrets/get.rs, crates/bitwarden/src/secrets_manager/secrets/get_by_ids.rs, crates/bitwarden/src/secrets_manager/secrets/list.rs, crates/bitwarden/src/secrets_manager/secrets/sync.rs, crates/bitwarden/src/secrets_manager/secrets/update.rs, crates/bws/src/main.rs
With the mutability changes to the client, we don't need a Mutex in `bitwarden-json` anymore either, which means we can remove the `async-lock` dependency as well.
team …
=> Remove Mutex from bitwarden-json

crates/bitwarden-vault/src/cipher/attachment.rs
https://bitwarden.atlassian.net/browse/PM-8874
Set the attachment size after we encrypt the contents
team
issue …
=> [PM-8874] Set attachment size when encrypting

crates/bitwarden-cli/README.md, crates/bitwarden-core/README.md, crates/bitwarden-fido/README.md, crates/bitwarden-json/src/client.rs, crates/bitwarden-send/README.md, crates/bitwarden-uniffi/src/lib.rs, crates/bitwarden-vault/README.md, crates/bitwarden/README.md, crates/bitwarden/src/auth/api/request/auth_request_token_request.rs, crates/bitwarden/src/auth/api/request/password_token_request.rs, crates/bitwarden/src/auth/login/password.rs, crates/bitwarden/src/client/client.rs, crates/bitwarden/src/client/client_settings.rs, crates/bitwarden/src/util.rs, crates/bw/src/main.rs, crates/bws/src/main.rs, crates/sdk-schemas/src/main.rs
Now that we expose `ClientSettings` and `DeviceType` directly in the root `bitwarden` crate we can make the `client_settings` module private. I also added `README` files to the newly created crates that missed them.
team
- ❓ (`:question:`) for …
=> Remove calls to client_settings namespace

crates/bitwarden-send/Cargo.toml, crates/bitwarden-vault/Cargo.toml, crates/bitwarden-vault/src/cipher/cipher.rs
This PR fixes some compilation errors when compiling individual crates using `cargo c -p crate-name`:
- `send` and `vault` were missing some features of `chrono`, these features are available in other crates in the workspace so when compiling the entire workspace it works, but it returns an error when compiling the individual crates
- `fido` depended on some functions from `vault` that were behind a `uniffi` feature.
Rust-analyzer will try to compile the crate individually when manually running a test, which is how I notice that this problem was occurring.
- Used …
=> Fix individual crate compilation

Cargo.lock, crates/bitwarden-fido/Cargo.toml, crates/bitwarden-fido/src/authenticator.rs, crates/bitwarden-fido/src/lib.rs, crates/bitwarden-fido/src/traits.rs, crates/bitwarden-fido/src/types.rs, crates/bitwarden-fido/src/uniffi_support.rs, crates/bitwarden-uniffi/src/platform/fido2.rs, crates/bitwarden/src/error.rs, crates/bitwarden/src/platform/client_fido.rs, crates/bitwarden/src/platform/mod.rs
This PR adds a function on the Fido2 authenticator which returns all available credentials as a View tailored specifically for integrating with OS-level autofill APIs
team …
=> Add fido2 credential autofill view

Cargo.lock, crates/bitwarden-api-api/Cargo.toml, crates/bitwarden-api-identity/Cargo.toml, crates/bitwarden-fido/Cargo.toml, crates/bitwarden-generators/Cargo.toml, crates/bitwarden-vault/Cargo.toml, crates/bitwarden/Cargo.toml
https://bitwarden.atlassian.net/browse/PM-8092
The new release of `reqwest` yesterday now unblocks our update to `rustls-platform-verifier` 0.3.1
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open …
=> [PM-8092] Update reqwest and rustls platform verifier

.github/workflows/publish-rust-crates.yml
GitHub actions only supports 10 inputs to a workflow_dispatch. As we keep adding packages we've exceeded this limit. Since we no longer need the functionality to release individual packages this PR removes the option all together and instead will always release all packages.
In case a package with the same version already exists in crates.io, cargo release won't attempt to publish it and continue on with the other packages.
- Updated any necessary …
=> Always deploy all rust packages

crates/bitwarden-fido/src/authenticator.rs, crates/bitwarden-fido/src/traits.rs, crates/bitwarden-uniffi/src/platform/fido2.rs, languages/swift/iOS/App/ContentView.swift
`check_user_and_pick_credential_for_creation` needs to return the result of the `check_user` part of the function
team …
=> [PM-9498] let user check and pick credential for creation return user check

crates/bitwarden-core/src/client/test_accounts.rs, crates/bitwarden-crypto/src/keys/master_key.rs
https://bitwarden.atlassian.net/browse/PM-9529
Add support for legacy user keys encrypted as AES-CBC-256-B64
team …
=> [PM-9529] Add support for legacy user keys encrypted as AES-CBC-256-B64

Cargo.lock, crates/bitwarden-core/Cargo.toml, crates/bitwarden-fido/Cargo.toml, crates/bitwarden-fido/src/authenticator.rs, crates/bitwarden-fido/src/types.rs
Updates to the latest passkey-rs version and now correctly returns `attestation_object`
team
issue and could …
=> [PM-9499] fix passkey-rs and sdk not returning cbor encoded attestation object

crates/bitwarden-core/src/auth/auth_request.rs, crates/bitwarden-core/src/auth/login/api_key.rs, crates/bitwarden-core/src/auth/login/password.rs, crates/bitwarden-core/src/auth/mod.rs, crates/bitwarden-core/src/auth/password/validate.rs, crates/bitwarden-core/src/auth/register.rs, crates/bitwarden-core/src/client/internal.rs, crates/bitwarden-core/src/mobile/client_kdf.rs, crates/bitwarden-core/src/mobile/crypto.rs, crates/bitwarden-core/src/mobile/kdf.rs, crates/bitwarden-core/src/platform/generate_fingerprint.rs, crates/bitwarden-core/src/platform/get_user_api_key.rs, crates/bitwarden-crypto/src/keys/master_key.rs, crates/bitwarden-crypto/src/keys/pin_key.rs, crates/bitwarden-send/src/send.rs, crates/memory-testing/src/main.rs
https://bitwarden.atlassian.net/browse/PM-9540
We should trim and convert emails to lowercase prior to using them as salt for the login and registration methods. Which matches the behaviour of our existing applications, https://github.com/bitwarden/clients/blob/main/apps/cli/src/auth/commands/login.command.ts#L575.
team
- 👍 (`:+1:`) or similar for great …
=> [PM-9540] Trim and lowercase email before using as salt

crates/bws/README.md
Using `cargo install bws` can cause issues if any minor dependency update has breaking changes. This was the case with #888.
By using `--locked`, we make cargo use the `Cargo.lock` file in the package, ensuring any builds use the same dependencies as we tested with.
team
- 📝 (`:memo:`) or ℹ️ …
=> Use --locked in installation docs

crates/bitwarden-core/src/auth/auth_request.rs, crates/bitwarden-core/src/auth/client_auth.rs, crates/bitwarden-core/src/auth/password/validate.rs, crates/bitwarden-core/src/auth/renew.rs, crates/bitwarden-core/src/client/encryption_settings.rs, crates/bitwarden-core/src/mobile/crypto.rs, crates/bitwarden-crypto/src/error.rs, crates/bitwarden-crypto/src/keys/key_encryptable.rs, crates/bitwarden-exporters/src/export.rs, crates/bitwarden-fido/src/authenticator.rs, crates/bitwarden-send/src/client_sends.rs, crates/bitwarden-send/src/send.rs, crates/bitwarden-sm/src/projects/create.rs, crates/bitwarden-sm/src/projects/project_response.rs, crates/bitwarden-sm/src/projects/update.rs, crates/bitwarden-sm/src/secrets/create.rs, crates/bitwarden-sm/src/secrets/list.rs, crates/bitwarden-sm/src/secrets/secret_response.rs, crates/bitwarden-sm/src/secrets/update.rs, crates/bitwarden-vault/src/cipher/cipher.rs, crates/bitwarden-vault/src/collection.rs, crates/bitwarden-vault/src/mobile/client_attachments.rs, crates/bitwarden-vault/src/mobile/client_ciphers.rs, crates/bitwarden-vault/src/mobile/client_collection.rs, crates/bitwarden-vault/src/mobile/client_folders.rs, crates/bitwarden-vault/src/mobile/client_password_history.rs
This change adds the organization UUID to the `MissingKey` error type, and changes the `get_key` function to return a Result instead of an Option to avoid having to add the error all over the place.
Note that some of the `encryption_settings.get_key()` calls were being mapped to `VaultLocked`, that wasn't correct as having the `EncryptionSettings` means the vault is unlocked. Those were changed to `MissingKey(id)` as well.
- Updated any necessary …
=> Return a more detailed MissingKey error from get_key()

.github/workflows/build-go.yaml, .github/workflows/release-go.yml, languages/go/example/go.mod, languages/go/go.mod
https://bitwarden.atlassian.net/browse/SM-1288
Follow-up of SM-1288 to update the Go version requirements in our wrapper and example project.
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open …
=> update go version in SDK and example project

crates/bitwarden-fido/src/authenticator.rs, crates/bitwarden-fido/src/lib.rs, crates/bitwarden-vault/src/cipher/login.rs
Like the title says, `fido2Credential.discoverable` was hardcoded, but should be set from `options`
team
issue …
=> fix: `discoverable` should not be hard coded

Cargo.lock, crates/bitwarden-py/Cargo.toml, crates/bitwarden-py/src/client.rs, crates/bitwarden-py/src/python_module.rs
https://bitwarden.atlassian.net/browse/SM-1327
Update all PYO3 dependencies and fix the necessary deprecation notices.
Thanks @Thomas-Avery and @dani-garcia for the collaboration!
team …
=> SM-1327: Fix PYO3 Deprecation

crates/bitwarden-core/src/auth/client_auth.rs, crates/bitwarden-core/src/auth/mod.rs, crates/bitwarden-core/src/auth/pin.rs, crates/bitwarden-uniffi/src/auth/mod.rs
https://bitwarden.atlassian.net/browse/PM-9527
Fede mentioned on Slack some time ago that we currently don't have a simple way to validate the user's PIN like we do with the password. Instead the way to do it was to call `init_crypto` and check that the result is not an error.
This requires more data than needed and does a lot of unnecessary operations, so I think it makes sense to expose a simpler way to do PIN verification.
In this PR we're decrypting the PIN protected user key and comparing it with the stored user key, similar to what we're doing with `validate_password_user_key`.
- Protected functional changes with optionality (feature …
=> [PM-9527] Add PIN validation support

crates/bws/CHANGELOG.md, crates/bws/src/command/secret.rs
https://bitwarden.atlassian.net/browse/SM-1338
With the introduction of individual secret permissions, it is possible for a machine account to have **read, write** permission on an unassigned secret. 
Editing this unassigned secret should be supported by `bws`.
This removes the client side validation that restricted the edit of an unassigned secret.
team …
=> [SM-1338] Add the ability to edit unassigned secrets

languages/go/secrets.go, package-lock.json, package.json, support/scripts/schemas.ts
https://bitwarden.atlassian.net/browse/SM-1370
The purpose of this PR is to update the`QuickType` version.
Most language generated schemas were not effected. 
A minor change in the error message for enum parsing.
```
default: throw std::runtime_error("This should not happen");
```
to
```
default: throw std::runtime_error("Unexpected value in enumeration \"[object Object]\": " + std::to_string(static_cast<int>(x)));
```
Has several breaking changes.
Previously, the `omit-empty` feature was enabled by default.
QuickType's description: `If set, all non-required objects will be tagged with ",omitempty"`
For example, the `SecretsSyncRequest` struct `LastSyncedDate` is optional and uses `emitempty`.
```
type SecretsSyncRequest struct {
// Optional date time a sync last occurred …
```
=> [SM-1370] Update QuickType version

crates/bitwarden-crypto/src/error.rs, crates/bitwarden-vault/src/cipher/cipher.rs
https://bitwarden.atlassian.net/browse/PM-10446
Add support for identifying if a login has a fido credential.
team …
=> [PM-10446] Add fido flag to CipherListView

crates/bitwarden-core/src/client/internal.rs
Just discovered that [`Arc::make_mut`](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.make_mut) exists, and it will reuse the `Arc` if it's the only strong reference to it, or clone it if there's more.
Previously we were always cloning the value, so this should help avoid some clones, as I don't expect any references to these arcs to be held long.
- Updated any necessary documentation (Confluence, contributing docs) or informed the …
=> Use Arc::make_mut to try to avoid unnecessary clones

README.md
https://bitwarden.atlassian.net/browse/SM-1399
Just `cargo build` is not sufficient for building the SDK on Windows on ARM. We should add clarity to what is required so that `cargo build` will run successfully.
Python is required. Clang is also required for [ring](https://crates.io/crates/ring) (more info [here](https://github.com/briansmith/ring/blob/main/BUILDING.md)).
- Updated any necessary documentation (Confluence, contributing docs) or informed …
=> [SM-1399] Update the README for Windows on ARM

Cargo.lock, crates/bitwarden-core/Cargo.toml
There is a new release of security-framework available which removes the need for us to manually specify the version.
team …
=> Remove locked security framework

crates/bitwarden-json/src/client.rs, crates/bitwarden-json/src/command.rs, crates/sdk-schemas/src/main.rs
https://bitwarden.atlassian.net/browse/SM-1275
As requested internally, this updates `AccessTokenLogin` to `LoginAccessToken` for all SM language bindings. This will break functionality for each binding on main until they are each updated (or unless they are already updated). We are reviewing all bindings now and updates for all are on deck. There are a total of ~8 bindings to verify and update for SM, so the only alternative is including all changes in one PR, which would be nice to avoid.
@Hinton please let us know if there is anything we are missing with this PR, besides subsequent PR's to fix this for each binding. Is there anything else that should be updated?
**Note**: we should not merge this if we plan to release any bindings before the subsequent updates come through.
- …
=> [SM-1275] Update AccessTokenLogin to LoginAccessToken for SM

crates/bws/src/cli.rs, crates/bws/src/command/mod.rs, crates/bws/src/config.rs, crates/bws/src/main.rs, crates/bws/src/state.rs, crates/bws/src/util.rs
https://bitwarden.atlassian.net/browse/SM-1174
This PR switches `bws` to use access token login state by default. This will help prevent many users from running into rate limiting issues. The two related config keys in a profile:
- `state_dir` -> this is the same as it has been; a custom directory for where state files will be stored
- `state_opt_out` -> this is a new key. If it's `true` or `1`, state files will not be used
**Note**: the `gnu` build failures are already happening on `main` and have been brought up internally
- Used internationalization (i18n) for all UI …
=> [SM-1174] Access Token Login State by Default in bws

crates/bitwarden-core/src/auth/client_auth.rs, crates/bitwarden-core/src/auth/key_connector.rs, crates/bitwarden-core/src/auth/mod.rs, crates/bitwarden-core/src/mobile/client_crypto.rs, crates/bitwarden-core/src/mobile/crypto.rs, crates/bitwarden-crypto/src/keys/master_key.rs, crates/bitwarden-uniffi/src/auth/mod.rs, crates/bitwarden-uniffi/src/crypto.rs
https://bitwarden.atlassian.net/browse/PM-10929
Add support for Key Connector.
- Adds support for `KeyConnector` to `initialize_user_crypto`.
- Support generating a random master key that can be sent to the key connector.
- Support getting the current master key and sending it to the key connector.
team
- 📝 …
=> [PM-10929] Support Key Connector

crates/bitwarden-c/src/c.rs, crates/bitwarden-py/src/client.rs, languages/go/bitwarden_client.go
https://bitwarden.atlassian.net/browse/SM-1413
Through the C FFI, we were running into concurrency issues with multiple Tokio runtimes.
A draft PR showing the concurrency issue with instructions can be found [here](https://github.com/bitwarden/sdk/pull/955).
This PR fixes this issue for `bitwarden-c` and `bitwarden-py`, by preserving the runtime. Thanks @dani-garcia for the fix and working together on this one!
This also refactors the `AccessTokenLogin` type as a follow up for testing purposes for Go as initiated by [this](https://github.com/bitwarden/sdk/pull/953) PR.
- Used …
=> [SM-1413] Resolve Concurrency Issues in C FFI

languages/python/bitwarden_sdk/bitwarden_client.py, languages/python/example.py
https://bitwarden.atlassian.net/browse/SM-1405
Update the Python wrapper to use bindings that are consistent. This will be a breaking change, as it does the following:
- replaces `access_token_login()` with `auth().login_access_token()` to be more consistent with the newer auth method we use in the base SDK.
- reorders the `create()` and `update()` args for secrets and projects, with arguments that are most consistently required between methods (eg. `organization_id`) first.
- `secrets.create(key, note, organization_id, value, project_ids)` -> `secrets.create(organization_id, key, value, note, project_ids)`
- `secrets.update(id, key, note, organization_id, value, project_ids)` -> `secrets.create(organization_id, id, key, value, note, project_ids)`
- `projects.create(name, …
=> breaking: Review and update Python sdk

.github/workflows/build-python-wheels.yml
#947 included an update to PYO3/maturin, which has changed how the Python wheels are packaged. The newer packages are producing a `not a supported wheel on this platform` error when we attempt to install them. This PR reverts to a known-working version of the PYO3/maturin action in order to resolve the breakage to the wheel package.
team
- 👍 (`:+1:`) or …
=> fix: broken python wheels

.github/workflows/rust-test.yml, crates/bitwarden-core/src/client/encryption_settings.rs
Napi broke tests for some reason, this seems unrelated to the code changes as I now get the same error on older branches. I believe this is related to the recent runner image update on github.
team
- 🤔 …
=> Attempt to fix compile

crates/bitwarden-core/src/client/encryption_settings.rs, crates/bitwarden-core/src/client/internal.rs, crates/bitwarden-core/src/mobile/client_crypto.rs, crates/bitwarden-core/src/mobile/crypto.rs, crates/bitwarden-uniffi/src/crypto.rs, crates/bitwarden-vault/src/sync.rs
Follow up to #1024, which improves the error message when missing a private key.
team
issue and could potentially …
=> Add explicit error for no private key

.github/workflows/build-swift.yml, .github/workflows/release-swift.yml
https://bitwarden.atlassian.net/browse/BRE-296
Fix `release-swift.yml` workflow
team
issue and could potentially …
=> [BRE-296] Fix release-swift workflow

.github/workflows/build-rust-cross-platform.yml
[//]: # (https://bitwarden.atlassian.net/browse/SM-1434)
The bitwarden-c lib is dynamically-linked with the version of GCC/Clang that is installed on the GitHub runner. Using newer runners will result in errors like this, for those that are running older, but still-supported versions of macOS:
```
object file (/Users/user/go/pkg/mod/github.com/bitwarden/sdk-go@v1.0.0/internal/cinterface/lib/darwin-x64/libbitwarden_c.a[216](8912af01511d326c-sha256-x86_64-macosx.o)) was built for newer 'macOS' version (14.2) than being linked (14.0)
```
This PR uses `MACOSX_DEPLOYMENT_TARGET` to support older versions of macOS.
- Protected functional changes …
=> [SM-1434] - Dynamically-linked bitwarden-c not working for older supported OS versions

.github/workflows/build-cli.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-314?atlOrigin=eyJpIjoiMTMyMTQ0ZmJmMzY0NGZkYTljOGJjNzljMzkyZTA0ZmUiLCJwIjoiaiJ9)
This PR fixes the Build CLI workflow so that it produces a proper universal signed binary for macOS.  I have tested the artifacts from [this](https://github.com/bitwarden/sdk/actions/runs/10889901254) build and they work both on my M2 MacBook and my Intel MacBook.
- Updated any necessary documentation (Confluence, …
=> BRE-314 - Fix Universal CLI Build

.github/workflows/build-cli-docker.yml, .github/workflows/build-cli.yml, .github/workflows/publish-ruby.yml, .github/workflows/release-cli.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-330?atlOrigin=eyJpIjoiZDg4YTQyYmU4MGY5NDEzNzkxNjRjMjEwOGE0NDMxZTciLCJwIjoiaiJ9)
This PR updates the workflows for building and releasing the bws CLI from the `main` branch.
team
- ❓ …
=> Update CLI workflows to be able to release from main branch

Cargo.lock, crates/bitwarden-fido/Cargo.toml, crates/bitwarden-fido/src/client.rs, crates/bitwarden-fido/src/lib.rs, crates/bitwarden-fido/src/types.rs, crates/bitwarden-uniffi/src/platform/fido2.rs
Add support for the new `Origin` type in `passkey-rs`
Points to: https://github.com/bitwarden/passkey-rs/pull/16
team …
=> [PM-11922] Handle apk key hash as origin

.github/workflows/build-rust-cross-platform.yml, Cargo.toml
https://bitwarden.atlassian.net/browse/SM-1444
Windows GNU builds are currently broken due to a bug in [rustls-platform-verifier](https://github.com/rustls/rustls-platform-verifier) when LTO is turned on.
I have submitted a GH Issue for this here: https://github.com/rustls/rustls-platform-verifier/issues/141
team …
=> [SM-1444] Fix Windows GNU Builds

languages/go/internal/cinterface/bitwarden_library.go
https://bitwarden.atlassian.net/browse/SM-1445
Go builds on Windows are failing, this PR adds the needed libraries that are missing.
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry …
=> [SM-1445] Fix Go build on Windows

crates/bitwarden-uniffi/src/lib.rs, languages/kotlin/sdk/build.gradle, languages/kotlin/settings.gradle
We've run into some issues related to rustls-platform-verifier distributing an android library through their crate, which works great if you use platform-verifier within an application. However since we distribute an sdk, the application have difficulties locating the android specific platform-verifier library.
To resolve this we follow the method established in https://github.com/rustls/rustls-platform-verifier/issues/115 and bundle the classes with the library.
- Communicated to DevOps any deployment …
=> Bundle platform-verifier

.github/workflows/build-swift.yml
https://bitwarden.atlassian.net/browse/BRE-339
When unpack the created artifact it takes the name of the zip file. It should unpack as `BitwardenFFI.xcframework`.
team …
=> [BRE-339] Fix Swift release workflow - artifact zip

crates/bitwarden-crypto/src/keys/shareable_key.rs
None.
Currently, the temporary buffer used for deriving shareable keys is [manually zeroized](https://github.com/bitwarden/sdk/blob/76417172489d5790babbe14bb8c6ad8b3aac2a33/crates/bitwarden-crypto/src/keys/shareable_key.rs#L32-L33). While documentation indicates that preceding `expect` calls cannot fail, this still seems brittle to future changes.
This PR places the buffer into a `Zeroizing` wrapper. It is still the case that zeroization may not occur on a panic, but this was already the case with the existing implementation, which would never zeroize in such a case.
- Used …
=> Improve zeroization of key buffer

.github/workflows/publish-php.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-341?atlOrigin=eyJpIjoiNGU4YTg0YWIxZGZkNGZjNmI0Nzc4ZGI1OGEzMWJiMTYiLCJwIjoiaiJ9)
This PR updates the Publish PHP workflow to allow releasing from the `main` branch instead of the `rc` branches.
team
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or …
=> BRE-341 - Update Publish PHP workflow

languages/kotlin/publish-local.sh, languages/kotlin/sdk/build.gradle
https://bitwarden.atlassian.net/browse/PM-12576
Support publishing to local maven repository.
team
issue and …
=> [PM-12576] Support publishing gradle to local maven repository

.github/workflows/build-java.yml, .github/workflows/publish-java.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-345?atlOrigin=eyJpIjoiNWI0OTA4Yjg1YzE1NDViN2FiZGM1NzlhMTZmMTViYTciLCJwIjoiaiJ9)
This PR updates the Java Build and Publish workflows in order to have the correct logic.
team
- ❓ …
=> BRE-345 - Update Java workflows

.github/workflows/release-python.yml
This PR updates the Release Python SDK workflow to fix some logic. The version in the `setup` job was being echoed to `GITHUB_ENV` instead of `GITHUB_OUTPUT`. The downloaded artifacts were all in separate directories, so I moved them all to a single directory to allow them to be uploaded to the GitHub release draft.
team
- 👍 (`:+1:`) or similar for great …
=> Release Python Workflow - Fix logic

Cargo.toml, crates/bitwarden-api-api/Cargo.toml, crates/bitwarden-api-identity/Cargo.toml, crates/bitwarden-core/Cargo.toml, crates/bitwarden-crypto/Cargo.toml, crates/bitwarden-exporters/Cargo.toml, crates/bitwarden-fido/Cargo.toml, crates/bitwarden-generators/Cargo.toml, crates/bitwarden-json/Cargo.toml, crates/bitwarden-napi/Cargo.toml, crates/bitwarden-py/Cargo.toml, crates/bitwarden-send/Cargo.toml, crates/bitwarden-sm/Cargo.toml, crates/bitwarden-uniffi/Cargo.toml, crates/bitwarden-vault/Cargo.toml, crates/bitwarden/Cargo.toml, crates/bw/Cargo.toml, crates/bws/Cargo.toml, crates/sdk-schemas/Cargo.toml, crates/uniffi-bindgen/Cargo.toml
To ensure we use consistent version ranges we should concentrate common dependencies to the root cargo.toml. This should make it easier to maintain the SM dependency ranges.
team …
=> Move common dependencies to the root cargo.toml

.github/workflows/release-napi.yml
This PR updates the Release @bitwarden/sdk-napi workflow to properly upload all of the artifacts to the GitHub draft release.
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not …
=> Release @bitwarden/sdk-napi workflow - Fix logic

crates/memory-testing/cases.json, crates/memory-testing/src/bin/capture-dumps.rs
Previously the memory testing program wouldn't detect when the binary being executed panicked unexpectedly, which caused the program to run indefinitely while waiting for the binary to notify it to continue. 
This started appearing when adding the validation for KDF minimums, as one of the tests we run is under the minimum, which causes CI to run until timeout: https://github.com/bitwarden/sdk/actions/runs/11109271931
- Updated any necessary …
=> Fix panic handling during memory testing

.github/workflows/build-rust-cross-platform.yml
This PR splits the upload artifact step into two, in order to have a single path defined for each action.  This makes sure that the artifact folder names are not changed during upload. [Test run](https://github.com/bitwarden/sdk/actions/runs/11130466715).
team
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for …
=> Fix Build Rust Cross Platform Upload

.github/workflows/publish-bws.yml, .github/workflows/publish-dotnet.yml, .github/workflows/publish-rust-crates.yml, .github/workflows/release-dotnet.yml
=> Format workflows

.github/workflows/publish-internal.yml, crates/bitwarden-wasm-internal/build.sh
[bitwarden.atlassian.net/browse/PM-12967](https://bitwarden.atlassian.net/browse/PM-12967)
We expect to automate this so that every merge to main will publish a new sdk-internal release. Therefore we want to:
- Not create github releases
- Publish to GH packages
team
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) …
=> Fix publish internal

.github/workflows/publish-internal.yml, languages/js/sdk-internal/package.json
=> Set version when publishing

.github/workflows/publish-internal.yml, languages/js/sdk-internal/LICENSE, languages/js/sdk-internal/README.md, languages/js/sdk-internal/package.json
It's a hassle to consume an package published on GitHub Packages in GitHub Actions as you need a PAT. Proposing we switch to publishing on npm instead.
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for …
=> Switch to using npm for sdk-internal

.github/workflows/build-cpp.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-359?atlOrigin=eyJpIjoiZGYxYzMxNjk4NGJiNDlmOGFiYmFjNWNhZDNmNTI4MTgiLCJwIjoiaiJ9)
This PR updates the Build C++ workflow to update the logic around the `bitwarden-c` library to reflect the removal of the `release` folder.
team
- 📝 (`:memo:`) or ℹ️ …
=> BRE-359 - Update Build C++ workflow

Cargo.lock, crates/bitwarden-wasm-internal/Cargo.toml, crates/bitwarden-wasm-internal/src/client.rs
In preparation for the bitwarden crate being removes we can stop depending on it in wasm-internal.
team
issue and …
=> Remove direct dependency to bitwarden in wasm-internal

crates/bitwarden-wasm-internal/src/crypto.rs, crates/bitwarden-wasm-internal/src/error.rs
=> Generic wasm error alternative

.github/workflows/publish-java.yml, languages/java/build.gradle
- [Card](https://bitwarden.atlassian.net/browse/BRE-367?atlOrigin=eyJpIjoiOWYxNzVkNWI1ZGVmNDdkZDk2Y2E4MTg5NGQ2MTgwMTEiLCJwIjoiaiJ9)
This PR updates the regex in the Publish Java workflow to match semver instead of calver. I also updated the `build.gralde` file to remove the `rc` branch references.
team
- 📝 …
=> BRE-367 - Update regex in Publish Java workflow

crates/bws/CHANGELOG.md
As discussed in PR https://github.com/bitwarden/sdk/pull/1122, add a link to our docs about the opt out change.
team …
=> Add opt out docs link to the bws changelog

languages/java/build.gradle
- [Card](https://bitwarden.atlassian.net/browse/BRE-367?atlOrigin=eyJpIjoiMzIwYjU3NTRiOGE3NGE3ZWI5YWFmMTljOWFmYTNiYmMiLCJwIjoiaiJ9)
This PR updates the `build.gradle` script to use the version number.  The way our Publish Java SDK workflow works is that it never checks out `main`, which made the Gradle script always use `-SNAPSHOT` in the URL which is not valid.
- Updated any necessary documentation (Confluence, contributing docs) or informed the …
=> BRE-367 - Update logic to use version only

.github/workflows/build-wasm-internal.yml, .github/workflows/build-wasm.yml
=> fix: wasm2js breaking wasm builds

.github/workflows/rust-test.yml
[BRE-393 Update sdk repository from macOS 12 to 14](https://bitwarden.atlassian.net/browse/BRE-393)
Bumps the macOS version for the Rust tests from 12 to 14 as 12 will be deprecated by Github on 12/3/24 with brownouts beginning 11/4/24.
https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/ 
- Updated any necessary documentation (Confluence, contributing docs) or informed the …
=> BRE-393 - Bumping macOS runner version from 12 to 14

.github/CODEOWNERS
https://bitwarden.atlassian.net/browse/PM-14839
Update the ownership of various Github actions such that:
1. Platform is responsible for build jobs
2. BRE and Platform are responsible for release jobs
This lines up with the CI/CD Partnership Model initiative.
CI jobs are failing, but they are on `main` too and the failures are unrelated to this work.  …
=> chore(codeowners): update ownership of various github actions

.github/workflows/build-cli-docker.yml, .github/workflows/publish-bws.yml
https://bitwarden.atlassian.net/browse/VULN-130
Signs Unified container images built off `main` with [Cosign](https://github.com/sigstore/cosign). This uses Sigstore's in-house certificate authority with short-lived keys that are all self-managed with the tool, which will also utilize GitHub's provided OIDC entity. As part of an effort to increase transparency of what we build as an open source company, these signatures are also sent to [Rekor](https://search.sigstore.dev/) -- users of our images are then free to verify the images against that log.
Also throws in container security scanning as that's adjacent in other builds.
- Protected …
=> Sign main branch Unified container builds with cosign and perform security scanning

.github/workflows/publish-dotnet.yml, .github/workflows/release-dotnet.yml
Change name of the .NET nupkg package. This is leftover after a repo and packages rename.
team
issue and could …
=> Fix dotnet nupkg name in publish and release workflows

.github/workflows/build-cli.yml, .github/workflows/build-go.yaml
https://github.com/actions/runner-images/issues/11101
The ubuntu-20.04 runner will be removed from GitHub on April 1st. This PR updates the ubuntu version to 22.04
The pinned version of actions/cache was a version behind what we're using everywhere else and has been deprecated by Github, so that's been updated to resolve one of the tests that was failing. …
=> Updating github runner from 20.04 ahead of deprecation

crates/bws/src/command/secret.rs
https://bitwarden.atlassian.net/browse/SM-1484
We currently panic if we call `get_by_ids()` if there are no secrets. This change avoids the unnecessary get request and instead outputs `[]` when there are no secrets, bringing the behavior of `bws secret list` in line with `bws project list` when there are no projects.
[![asciicast](https://asciinema.org/a/bEwxNjt9pVpW9JQsKqkfV9TON.svg)](https://asciinema.org/a/bEwxNjt9pVpW9JQsKqkfV9TON)
- Updated any …
=> fix: don't panic if there are no secrets

.github/workflows/build-cli.yml, .github/workflows/build-rust-cross-platform.yml
https://bitwarden.atlassian.net/browse/SM-1565
`goto-bus-stop/setup-zig` is no longer maintained. Switch to using `mlugg/setup-zig`, which is a maintained Action.
Also, update to latest stable Zig.
team
- 🤔 …
=> chore: use newer, maintained Zig setup Action

.github/workflows/build-python-wheels.yml, languages/python/pyproject.toml
https://bitwarden.atlassian.net/browse/SM-1540
Fixes the segfaults described in #1288 by building with `--zig` and lowering the `manylinux` compatibility settings from the explicitly defined `2_28` to `2_17`, [which is implied](https://www.maturin.rs/distribution.html?highlight=zig#build-wheels) when passing `--zig`.
team
- 👍 (`:+1:`) or similar for great …
=> fix: build with better manylinux compatibility to prevent segfaults on different linux environments
