bitwarden/sdk-sm

languages/js_webassembly/bitwarden_client/index.ts, languages/js_webassembly/index.ts, languages/js_webassembly/package.json, languages/js_webassembly/webpack.config.js
- Update WebAssembly to use camelCase.
- Adjust webpack to proxy requests.
=> Fix WebAssembly build

.github/ISSUE_TEMPLATE/cli.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/sdk.yml, .github/PULL_REQUEST_TEMPLATE.md
=> Add issue templates

crates/bitwarden/src/client/mod.rs, crates/bitwarden/src/sdk/auth/response/api_key_login_response.rs, crates/bitwarden/src/sdk/auth/response/password_login_response.rs, crates/bitwarden/src/sdk/response/projects_response.rs, crates/bitwarden/src/sdk/response/secrets_response.rs, crates/bitwarden/src/sdk/response/sync_response.rs, crates/bitwarden/src/sdk/response/user_api_key_response.rs
```
```
Make ClientSecrets and ClientProjects public so they appear correctly in the autogenerated docs.
Also hide the process_response functions which are internal only.
Fixes #37 
=> Expose ClientSecrets/Projects in docs and hide process_response

.github/workflows/build-rust-crates.yml, crates/bitwarden-json/Cargo.toml, crates/bitwarden-json/src/client.rs, crates/bitwarden/Cargo.toml, crates/bitwarden/src/client/client.rs, crates/bitwarden/src/commands/generate_fingerprint.rs, crates/bitwarden/src/commands/get_user_api_key.rs, crates/bitwarden/src/commands/login.rs, crates/bitwarden/src/commands/sync.rs, crates/bitwarden/src/sdk/request/command.rs, package.json
```
```
Move all experimental portions behind a internal feature flag to prevent accidental usage.
=> Add feature flag for internal commands

crates/bitwarden/README.md, crates/bitwarden/src/lib.rs
```
```
Update the SDK example in the README now that we are using the `uuid` crate. Specifically, the `SecretIdentifiersRequest.organization_id`'s type is now a `Uuid`.
- **README.md:** Update the readme example
- **lib.rs:** Add a check to test the readme docs
=> Update the SDK Example

.github/workflows/build-cli.yml, .github/workflows/build-rust-crates.yml, .github/workflows/rust-test.yml
```
```
- Update the CI workflow to move all the tests into the test workflow.
- Change the test workflow to remove parallel package execution.
- We have to re-build each dependency for each package which is slow
- Build > test time currently.
=> Move all tests to test workflow

.github/workflows/lint.yml
```
```
Make sure linting fails if links are broken in docs.
=> Catch broken links in docs

.github/workflows/build-napi.yml, .github/workflows/build-rust-crates.yml, .github/workflows/cloc.yml, .vscode/settings.json
```
```
Move CLOC job into a separate workflow to prevent it from being run twice.
=> Move cloc job to separate workflow

.github/workflows/enforce-labels.yml
```
```
Adds enforce-labels process workflow to our pipeline. This workflow allows us to tag special labels as un-mergeable.
=> Add enforce labels workflow

crates/bitwarden-json/src/command.rs, crates/bitwarden/src/client/encryption_settings.rs, crates/bitwarden/src/crypto.rs, crates/bitwarden/src/secrets_manager/projects/create.rs, crates/bitwarden/src/secrets_manager/projects/project_response.rs, crates/bitwarden/src/secrets_manager/projects/update.rs, crates/bitwarden/src/secrets_manager/secrets/create.rs, crates/bitwarden/src/secrets_manager/secrets/list.rs, crates/bitwarden/src/secrets_manager/secrets/secret_response.rs, crates/bitwarden/src/secrets_manager/secrets/update.rs
```
```
Extracted from #64
Implements a generic way to encryption and decryption of structs.
- Organization id changed to optional.
- Added Encryptable & Decryptable trait to support encrypting and decrypting multiple data types.
- Update existing places to use the new traits.
=> Extract encrypt/decrypt refactor from state PR

.github/workflows/direct-minimal-versions.yml, Cargo.toml
```
```
We should build using the minimum specified dependency versions to ensure our code is not using features available on more recent dependency versions.
Since bitwarden is a rust library we should strive towards not constantly updating patch and minor versions for dependencies.
=> Add workflow for testing direct minimal versions

.github/renovate.json
```
```
Set `rangeStrategy` to `widen` for cargo.
=> Set rangeStrategy to widen

.github/workflows/release-napi.yml
```
```
There were security changes around how Azure Key Vaults were accessed with GH secrets. This updates the napi release workflow to use the newest credentials and Azure Key Vault.
- **.github/workflows/release-napi.yml:** Update the napi release workflow with the newest credentials.
=> Update workflow credentials and key vault

.github/workflows/build-rust-crates.yml, .github/workflows/rust-test.yml, Cargo.lock, crates/bitwarden/src/auth/api/request/mod.rs, crates/bitwarden/src/auth/commands/login.rs, crates/bitwarden/src/client/client.rs, crates/bitwarden/src/client/encryption_settings.rs, crates/bitwarden/src/client/mod.rs, crates/bitwarden/src/crypto.rs, crates/bitwarden/src/util.rs, crates/bitwarden/src/wordlist.rs
```
```
Resolve all the build warnings when building without internal feature.
=> Fix warnings

CHANGELOG.md, crates/bitwarden/CHANGELOG.md, crates/bws/CHANGELOG.md
```
```
We should record a changelog for consumers of the crates that doesn't require a user to walk through gh releases.
=> Add changelogs

crates/bitwarden/CHANGELOG.md, crates/bws/CHANGELOG.md
```
```
Add 0.3.0 to the changelog.
=> Add 0.3.0 to changelog

crates/bitwarden-json/src/client.rs, crates/bitwarden-json/src/command.rs
```
```
Implement the folder encrypt JSON command, this was missing from the last PR
=> Implement folder encrypt command in the JSON mobile api

crates/bitwarden/src/vault/cipher/attachment.rs, crates/bitwarden/src/vault/cipher/card.rs, crates/bitwarden/src/vault/cipher/cipher.rs, crates/bitwarden/src/vault/cipher/field.rs, crates/bitwarden/src/vault/cipher/identity.rs, crates/bitwarden/src/vault/cipher/linked_id.rs, crates/bitwarden/src/vault/cipher/local_data.rs, crates/bitwarden/src/vault/cipher/login.rs, crates/bitwarden/src/vault/cipher/mod.rs, crates/bitwarden/src/vault/cipher/password_history.rs, crates/bitwarden/src/vault/cipher/secure_note.rs, crates/bitwarden/src/vault/mod.rs
```
```
Implement the model for Cipher, to be used in the mobile encryption/decryption API. This is already pretty big so I've extracted the encrypt/decrypt implementations to separate PRs coming after this one.
=> Add Cipher model for the Mobile API

crates/bitwarden/src/mobile/vault/folders/folder_decrypt.rs, crates/bitwarden/src/mobile/vault/folders/folder_decrypt_list.rs, crates/bitwarden/src/mobile/vault/folders/folder_encrypt.rs, crates/bitwarden/src/mobile/vault/folders/mod.rs
```
```
Rework the request response files in folders to be structured per command instead of type. Should be more flexible long term.
=> Rework folder request response structure

.github/workflows/build-rust-crates.yml, .github/workflows/release-napi.yml, .github/workflows/rust-test.yml
```
```
- **.github/workflows/build-rust-crates.yml:** Fix `ref` to `refs`
- **.github/workflows/release-napi.yml** Remove GitHub release publishing
- **.github/workflows/rust-test.yml** Add trigger on `rc` and `hotfix-rc` push.
=> Fix workflows

languages/kotlin/app/build.gradle, languages/kotlin/app/src/main/AndroidManifest.xml, languages/kotlin/app/src/main/java/com/bitwarden/myapplication/MainActivity.kt, languages/kotlin/build.gradle
```
```
Add some code samples doing prelogin/login/sync, initializing crypto and trying to decode some folders, so we can test the SDK and the uniffi bindings. The kotlin code is not the prettiest and doesn't handle any errors, but the SDK side works correctly
=> Add some SDK examples to the Android app

languages/swift/iOS/App/ContentView.swift, languages/swift/iOS/swift-format.json
```
```
Added SDK samples to the iOS application based on the android samples
=> [PM-3459] Add samples for ios app based on the android samples

languages/swift/build.sh
```
```
Build non simulator ios artifact
=> Also build non sim ios

crates/bitwarden-uniffi/README.md, crates/bitwarden-uniffi/src/lib.rs, crates/bitwarden-uniffi/src/tool/mod.rs, crates/bitwarden/src/lib.rs, crates/bitwarden/src/tool/client_generator.rs, crates/bitwarden/src/tool/mod.rs, crates/bitwarden/src/tool/password.rs, crates/bw/src/main.rs, languages/kotlin/doc.md, support/docs/docs.ts
```
```
Scaffold the password and passphrase generator. Wire up a command for password in the bw cli.
=> Scaffold generators

crates/bitwarden/src/vault/cipher/cipher.rs
=> Fix format

crates/bitwarden-uniffi/build.rs, crates/bitwarden-uniffi/src/auth/mod.rs, crates/bitwarden-uniffi/src/lib.rs, crates/bitwarden-uniffi/src/tool/mod.rs, crates/bitwarden/src/auth/client_auth.rs, crates/bitwarden/src/auth/mod.rs, crates/bitwarden/src/auth/password.rs, languages/kotlin/doc.md, support/docs/docs.ts
```
```
Scaffold:
- Password Strength
- Satisfies MP Policy
=> Scaffold password strength and policy

Cargo.lock, crates/bitwarden-uniffi/Cargo.toml, crates/bitwarden-uniffi/src/docs.rs, crates/bitwarden-uniffi/src/lib.rs, crates/bitwarden/src/auth/password.rs, crates/sdk-schemas/Cargo.toml, crates/sdk-schemas/src/main.rs, languages/kotlin/doc.md, support/docs/docs.ts, support/docs/template.hbs
```
```
When we removed the mobile commands from `bitwarden_json` the doc generation broke. Re-adding support for it.
=> Fix doc generation

crates/bitwarden-uniffi/src/auth/mod.rs, crates/bitwarden-uniffi/src/lib.rs, languages/kotlin/app/src/main/java/com/bitwarden/myapplication/MainActivity.kt, languages/kotlin/doc.md, languages/swift/iOS/App/ContentView.swift, support/docs/docs.ts
```
```
Move password_hash from kdf to auth.
=> Move KDF to auth

crates/bitwarden/src/auth/login/access_token.rs, crates/bitwarden/src/auth/login/api_key.rs, crates/bitwarden/src/auth/login/password.rs, crates/bitwarden/src/client/client.rs, crates/bitwarden/src/client/encryption_settings.rs, crates/bitwarden/src/crypto/enc_string.rs, crates/bitwarden/src/crypto/mod.rs, crates/bitwarden/src/error.rs, crates/bitwarden/src/mobile/crypto.rs, crates/bitwarden/src/mobile/mod.rs, crates/bitwarden/src/secrets_manager/projects/project_response.rs, crates/bitwarden/src/secrets_manager/secrets/list.rs, crates/bitwarden/src/secrets_manager/secrets/secret_response.rs, crates/bitwarden/src/uniffi_support.rs, crates/bitwarden/src/vault/cipher/attachment.rs, crates/bitwarden/src/vault/cipher/card.rs, crates/bitwarden/src/vault/cipher/cipher.rs, crates/bitwarden/src/vault/cipher/field.rs, crates/bitwarden/src/vault/cipher/identity.rs, crates/bitwarden/src/vault/cipher/login.rs, crates/bitwarden/src/vault/collection.rs, crates/bitwarden/src/vault/folder.rs, crates/bitwarden/src/vault/password_history.rs
```
```
Rename `CipherString` to `EncString` in an effort to be consistent with the other Bitwarden codebases.
=> Rename CipherString to EncString

crates/bitwarden/src/auth/login/access_token.rs, crates/bitwarden/src/client/access_token.rs, crates/bitwarden/src/client/client.rs, crates/bitwarden/src/client/encryption_settings.rs, crates/bitwarden/src/crypto/aes_opt.rs, crates/bitwarden/src/crypto/enc_string.rs, crates/bitwarden/src/crypto/mod.rs, crates/bitwarden/src/crypto/symmetric_crypto_key.rs
```
```
Move `SymmetricCryptoKey` and `AES` operations to the crypto module.
=> Move AES and SymmetricCryptoKey to crypto module

crates/bitwarden/src/crypto/mod.rs
```
```
Make a generic `hkdf_expand` method.
=> Make helper method for hkdf_expand

crates/bitwarden/src/crypto/enc_string.rs
```
```
Cleanup the `Display` implementation for `EncString`.
=> Cleanup enc string display

languages/kotlin/sdk/build.gradle
```
```
Checks for builds on `master` for certain versioning decisions.
- **languages/kotlin/sdk/build.gradle:** Conditional change.
=> Check for master branch with Maven builds

crates/bitwarden/src/auth/password.rs, crates/bitwarden/src/tool/generators/password.rs
```
```
Mock response values to allow stubbed implementation.
=> Mock response values for password strength and generators

.github/workflows/publish-dotnet.yml
```
```
Workflow used incorrect syntax for inputs.
=> Fix nuget workflow inputs

languages/csharp/Bitwarden.Sdk/Bitwarden.Sdk.csproj
```
```
LicenseUrl is deprecated and we should use LicenseFile instead.
=> Change LicenseUrl to LicenseFile

crates/bitwarden/CHANGELOG.md, crates/bws/CHANGELOG.md
```
```
Add 0.3.1 to the changelog.
=> Add 0.3.1 to changelog

Cargo.lock, crates/bitwarden-uniffi/Cargo.toml, crates/bitwarden-uniffi/src/docs.rs, crates/bitwarden-uniffi/src/lib.rs, crates/bitwarden-uniffi/src/uniffi_support.rs, crates/bitwarden-uniffi/src/vault/mod.rs, crates/bitwarden/src/mobile/vault/client_totp.rs, crates/bitwarden/src/mobile/vault/mod.rs, crates/bitwarden/src/vault/mod.rs, crates/bitwarden/src/vault/totp.rs, languages/kotlin/doc.md
```
```
Mock a TOTP implementation
=> Mock a TOTP implementation

Cargo.lock, crates/bitwarden/src/crypto/aes_ops.rs, crates/bitwarden/src/crypto/enc_string.rs, crates/bitwarden/src/crypto/encryptable.rs, crates/bitwarden/src/crypto/fingerprint.rs
```
```
Begin documenting the crypto module
=> Begin documenting the crypto module

.github/workflows/publish-rust-crates.yml, .github/workflows/release-cli.yml, .github/workflows/release-napi.yml, .github/workflows/version-bump.yml
```
```
This PR updates all of our action versions to reference `main` instead of `master`.
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)
=> All workflows - Update 'master' to 'main' for any actions in the gh-actions repository

Cargo.lock, Cargo.toml, crates/bitwarden-uniffi/src/vault/sends.rs
```
```
Update uniffi to solve the conflict between our `Send` and Rust's `Send`
=> Update uniffi to solve Send conflict

.github/renovate.json
```
```
Sync the renovate config to be inline with what's used in the other repositories.
=> Sync renovate config to be inline with other repos

.vscode/tasks.json
```
```
Fix invalid path in VSCode tasks
=> Fix VSCode tasks

Cargo.lock, Cargo.toml, crates/bitwarden-uniffi/Cargo.toml, crates/bitwarden/Cargo.toml, crates/uniffi-bindgen/Cargo.toml
```
```
This upgrade adds code comments to the generated uniffi code
=> Update uniffi to add comments support

crates/bitwarden-uniffi/src/docs.rs, crates/bitwarden-uniffi/src/lib.rs, crates/bitwarden-uniffi/src/platform/mod.rs, crates/bitwarden/src/client/client.rs, crates/bitwarden/src/platform/generate_fingerprint.rs, languages/kotlin/doc.md, support/docs/docs.ts
```
```
Expose the fingerprint method to uniffi.
=> [PM-4272] Expose fingerprint to uniffi

.gitignore
```
```
These files have to be copied in specific places when building the SDK bindings, and having them tracked by git is quite annoying.
=> Add binary files to gitignore

support/scripts/schemas.ts
Fix broken schema generation workflow from #399.
- **./support/scripts/schemas.ts:** Update the Python schemas dir
=> Fix broken schema generation

Cargo.lock, crates/bitwarden/Cargo.toml, crates/bitwarden/src/client/client_settings.rs
```
```
Seems to only be used for our docs.
=> Remove dependency on assert_matches

crates/bitwarden-uniffi/src/crypto.rs, crates/bitwarden/src/client/client.rs, crates/bitwarden/src/crypto/master_key.rs, crates/bitwarden/src/crypto/symmetric_crypto_key.rs, crates/bitwarden/src/mobile/client_crypto.rs, crates/bitwarden/src/mobile/crypto.rs, languages/kotlin/app/src/main/java/com/bitwarden/myapplication/MainActivity.kt, languages/kotlin/doc.md, languages/swift/iOS/App/ContentView.swift
```
```
Implement support for deriving the PIN encrypted user key and initializing crypto with it. Updated the mobile app demos to use this new functionality.
=> [PM-4694] Implement PIN unlock

crates/bws/CHANGELOG.md
```
```
Add env output item in the changelog
=> Update Changelog with env output item

.github/workflows/rust-test.yml
=> Wire up code coverage

crates/bitwarden-uniffi/src/auth/mod.rs, crates/bitwarden/src/auth/password.rs
```
```
Implements the validation for master password policy
=> [PM-3437] add validation for master password policy

crates/bitwarden/CHANGELOG.md, crates/bws/CHANGELOG.md
```
```
Changelog update for the release on 2023-12-21.
=> SM-1058: Update the changelog

.github/workflows/build-android.yml, .github/workflows/build-cli.yml
=> Install cross locked

crates/bitwarden-c/src/macros/mod.rs
```
```
Clippy warning in more recent rust versions.
=> Fix clippy warning

.github/codecov.yml
```
```
Ignore tools since they don't need to be tested.
=> Codecov ignore tools

crates/bitwarden/src/auth/api/request/mod.rs, crates/bitwarden/src/auth/jwt_token.rs, crates/bitwarden/src/auth/login/access_token.rs, crates/bitwarden/src/client/access_token.rs, crates/bitwarden/src/crypto/aes_ops.rs, crates/bitwarden/src/crypto/enc_string/asymmetric.rs, crates/bitwarden/src/crypto/enc_string/mod.rs, crates/bitwarden/src/crypto/enc_string/symmetric.rs, crates/bitwarden/src/crypto/master_key.rs, crates/bitwarden/src/crypto/rsa.rs, crates/bitwarden/src/crypto/symmetric_crypto_key.rs, crates/bitwarden/src/platform/generate_fingerprint.rs, crates/bitwarden/src/util.rs
```
```
Swap custom b64 config to standard
=> Swap custom b64 config to standard

languages/python/bitwarden_sdk/bitwarden_client.py
Enable authentication with the state file. Relates to #388.
- **`languages/python/bitwarden_sdk/bitwarden_client.py`**: Add optional `state_file_path` parameter to `access_token_login`
=> [SM-1076] - add `state_file_path` param to `access_token_login`

.github/workflows/build-cli-docker.yml
```
```
This PR updates the `build-cli-docker.yml` workflow to change the hash of `Bitwarden` actions to the `main` branch in the `gh-actions` repository.
- **.github/workflows/build-cli-docker.yml:** Update `Bitwarden` actions to point to the `main` branch.
=> Update Bitwarden action hashes to target 'main' branch

crates/bitwarden-generators/uniffi.toml
=> Add uniffi config for generators

languages/python/README.md
Fix errors in README and update the Python package name in preparation for publishing to PyPI.
=> Update Python README

crates/bitwarden-uniffi/src/auth/mod.rs, crates/bitwarden/src/auth/client_auth.rs, crates/bitwarden/src/auth/login/password.rs, crates/bitwarden/src/auth/login/two_factor.rs, crates/bitwarden/src/auth/mod.rs, crates/bitwarden/src/auth/password/mod.rs, crates/bitwarden/src/auth/password/validate.rs
```
```
Enables password validation without knowing the password hash by decrypting the user key.
=> Support validating password by decrypting user key

.github/workflows/build-android.yml, .github/workflows/build-java.yml
```
```
This action was moved for the `v3.0.0` release and the action name had to be updated in the workflows.
- **.github/workflows/build-android.yml:** Updated Gradle action path and hash.
- **.github/workflows/build-java.yml:** Updated Gradle action path and hash.
=> Update Gradle action as recommended in new release

.github/renovate.json
```
```
Use shared renovate config.
=> Use base renovate config

.github/renovate.json
Add Dockerfile to renovate config. Needed to keep the base Rust image up-to-date.
- **.github/renovate.json:** Add rules based on [server repo](https://github.com/bitwarden/server/blob/c0e5d19cb5fc6c44e2110bf4240b4e9e912e6b56/.github/renovate.json#L13-L15
).
=> Add dockerfile to renovate

.github/workflows/build-cli.yml
```
```
https://bitwarden.atlassian.net/browse/DEVOPS-1814
https://bitwarden.atlassian.net/browse/SM-1113
- **.github/workflows/build-cli.yml:** Change runner for linux CLI build for ubuntu-20.04
=> [DEVOPS-1814] Fix SM CLI for ubuntu 20.04

.github/workflows/publish-ruby.yml
```
```
- **.github/workflows/publish-ruby.yml:** Fix artifact parameter name, update `rubygems/release-gem` to fix publishing.
=> [DEVOPS-1785] Fix Ruby publish workflow

.github/workflows/publish-ruby.yml
```
```
Fix error from ruby release pipeline:
```
Could not find gem 'rspec (~> 3.0)' in locally installed gems.
```
- **.github/workflows/publish-ruby.yml:** Replace `gem build` with `bundle install`
=> [DEVOPS-1785] Fix publish Ruby workflow

.github/codecov.yml
```
```
We should make the patch check informational too.
=> Make codecov patch informational

.github/workflows/lint.yml, crates/bitwarden/src/client/client_settings.rs
```
```
Takes Clippy results as SARIF and uploads to GHAS for easier viewing and management.
- **.github/workflows/lint.yml:** New Cargo package usage and SARIF upload.
=> Export Clippy results as SARIF and upload

.github/codecov.yml
```
```
Reverts #634 and #636 as we found our mistake.
- **.github/codecov.yml:** Global configuration removal.
=> Undo global coverage setting application

.github/workflows/release-go.yml
```
```
This PR pins uses of Bitwarden actions to `main`.
- **.github/workflows/release-go.yml:** Pin Bitwarden actions to `main`.
=> Update bitwarden actions to main

.github/workflows/build-dotnet.yml, .github/workflows/publish-dotnet.yml
```
```
- **.github/workflows/build-dotnet.yml:** Trigger build on `rc` and `hotfix-rc` branches, get dotnet project version from `.csproj` while building.
- **.github/workflows/publish-dotnet.yml** Use build artifact during publish
=> Update dotnet build pipeline

crates/bitwarden-napi/README.md, crates/bws/src/main.rs
Rename instances (& similar) of "service account" to "machine account". This only impacts public facing text, so items in README's, documentation, help docs, etc.
=> [SM-1178] Rename Service Accounts to Machine Accounts

.github/workflows/publish-rust-crates.yml
```
```
We need to be able to publish these crates to release the SDK.
=> Add bitwarden-cli and bitwarden-exporters to publish-rust-crates

Cargo.lock, crates/bitwarden-cli/src/color.rs, crates/bws/Cargo.toml, crates/bws/src/main.rs, crates/bws/src/render.rs
```
```
Now that we are publishing the `bitwarden-cli` crate we should start using the shared functionality in the `bws` crate. And continually extract common code out from it.
=> Use the shared bitwarden-cli in bws

languages/java/build.gradle
```
```
In #703 we fixed the android java build, but forgot that java also needed to be updated.
=> Fix java build

.github/workflows/build-wasm.yml
```
```
Should be `refs/heads/main` not `refs/head/main`.
=> Fix if condition on wasm workflow

.vscode/settings.json
```
```
Use a separate target directory for rust-analyzer which prevents rust-analyzer check from blocking regular cargo commands.
=> Tell rust-analyzer to use a separate target dir

.github/workflows/publish-rust-crates.yml
=> Fix package names in publish-rust-crates.yml workflow

crates/bitwarden-cli/Cargo.toml
```
```
Add required `description` to `bitwarden-cli` crate.
=> Add description to bitwarden-cli crate

crates/bitwarden/src/mobile/crypto.rs
```
```
I've gone through all `key: String` in the codebase and these seems to be the last sensitive keys.
=> [PM-7723] Mark decrypted keys as sensitive

crates/bitwarden/CHANGELOG.md, crates/bws/CHANGELOG.md
```
```
Update the changelog date for the `0.5.0` release.
**Note**: the crates.io release happened on April 26, 2024. The GitHub release should have been published but was not until April 29, 2024. I used the official date from crates.io here.
=> Update changelog for 0.5.0 release

Cargo.lock, crates/bitwarden-uniffi/Cargo.toml, crates/bitwarden-uniffi/src/error.rs, crates/bitwarden-uniffi/src/platform/fido2.rs, crates/bitwarden-uniffi/src/platform/mod.rs, crates/bitwarden/Cargo.toml, crates/bitwarden/src/error.rs, crates/bitwarden/src/platform/client_platform.rs, crates/bitwarden/src/platform/fido2/authenticator.rs, crates/bitwarden/src/platform/fido2/client.rs, crates/bitwarden/src/platform/fido2/mod.rs, crates/bitwarden/src/platform/fido2/traits.rs, crates/bitwarden/src/platform/mod.rs, crates/bitwarden/src/vault/cipher/attachment.rs, crates/bitwarden/src/vault/cipher/card.rs, crates/bitwarden/src/vault/cipher/cipher.rs, crates/bitwarden/src/vault/cipher/field.rs, crates/bitwarden/src/vault/cipher/identity.rs, crates/bitwarden/src/vault/cipher/local_data.rs, crates/bitwarden/src/vault/cipher/login.rs, crates/bitwarden/src/vault/cipher/mod.rs, crates/bitwarden/src/vault/password_history.rs
```
```
Created passkeys Uniffi API layer
=> [WIP] Passkey Uniffi API layer

crates/bws/Cargo.toml
```
```
The CLI should use the same format for dependency versions.
=> Change dependency format for bws

Cargo.toml, crates/bitwarden-c/Cargo.toml
Reduce static library size when building the `bitwarden-c` crate.
- **crates/bitwarden-c/Cargo.toml:** Update the crate types for `bitwarden-c`
=> SM-1237: Decrease bitwarden-c static archive size

.github/workflows/build-cli.yml, .github/workflows/build-cpp.yml, .github/workflows/build-napi.yml, .github/workflows/build-python-wheels.yml, .github/workflows/build-rust-cross-platform.yml, .github/workflows/direct-minimal-versions.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-69)
- Upgrade MacOS Runners to v13
team
issue and could …
=> [BRE-69] - Upgrade to Macos-13 Runner

.github/workflows/release-go.yml, languages/go/README.md, languages/go/bitwarden_client.go, languages/go/command_runner.go, languages/go/example/example.go, languages/go/example/go.mod, languages/go/go.mod
[SM-1297](https://bitwarden.atlassian.net/browse/SM-1297)
Renames `sm-sdk-go` to `sdk-go` across the SDK. This should include GH workflows as well as any Rust / Go code.
team …
=> [SM-1297] Rename sm-sdk-go to sdk-go

.github/workflows/publish-python.yml
https://bitwarden.atlassian.net/browse/BRE-94
Replace `dawidd6/action-download-artifact` with `bitwarden/gh-actions/download-artifacts`
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry …
=> [BRE-94] Replace `dawidd6/action-download-artifact` with `bitwarden/gh-actions/download-artifacts`

Cargo.lock, crates/bitwarden-uniffi/Cargo.toml, crates/bitwarden-vault/uniffi.toml, languages/kotlin/app/src/main/java/com/bitwarden/myapplication/MainActivity.kt
#825 broke android.
team
- 🎨 (`:art:`) for suggestions / …
=> Fix android after bitwarden-vault PR

crates/bitwarden-uniffi/src/vault/ciphers.rs, crates/bitwarden/src/mobile/vault/client_ciphers.rs
=> Re-add `Fido2Credential` to uniffi

crates/bws/CHANGELOG.md
https://bitwarden.atlassian.net/browse/SM-1175
Add removal of deprecated commands to changelog.
team
issue and …
=> [SM-1175] Add sm-1175 to the bws changelog

languages/swift/iOS/App/ContentView.swift
We changed the Fido2 interfaces and forgot to update the Ios code.
team
issue and could potentially benefit from …
=> Fix ios not compiling after tweaks to fido

languages/csharp/global.json
Manually updating the .net version for the c# sdk, renovate had these updates disabled.
team
issue and could …
=> [sm-1253] Updating dotnet version

languages/python/README.md
Make some updates to the Python setup instructions
team
- 🎨 …
=> Update Python README.md

Cargo.lock, crates/bitwarden-sm/Cargo.toml
Remove uniffi from bitwarden-sm crate.
team
- 🎨 (`:art:`) for …
=> Remove uniffi from bitwarden-sm crate

crates/bitwarden-crypto/src/enc_string/symmetric.rs, crates/bitwarden-uniffi/src/vault/mod.rs, crates/bitwarden-vault/src/cipher/cipher.rs, crates/bitwarden-vault/src/client_totp.rs, crates/bitwarden-vault/src/lib.rs, crates/bitwarden-vault/src/totp.rs
https://bitwarden.atlassian.net/browse/PM-10447
Add totp to cipher list view, and a way to calculate the current value from a given list view.
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open …
=> [PM-10447] Add support for calculating totp from cipher list view

.github/workflows/build-android.yml
Build android is broken after the breaking changes introduced in #951. This PR follows the recommended changes and splits setup gradle into two steps.
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more …
=> Fix gradle deprecation

.github/workflows/minimum-rust-version.yml, crates/bitwarden/CHANGELOG.md, crates/bws/CHANGELOG.md
The #972 PR requires MSRV 1.73, and #924 will require. MSRV 1.75. To avoid upgrading twice I suggest immediately changing to 1.75. This is noted as a change in both the CLI and bitwarden change logs.
team
- 🤔 …
=> Bump MSRV to 1.75

.github/workflows/rustdoc.yml
https://bitwarden.atlassian.net/browse/PM-11247
Workflow for publishing rust api documentation.
team
issue and …
=> [PM-11247] Publish SDK api documentation

.github/workflows/build-swift.yml, .github/workflows/release-swift.yml
Fix SWIFT build & release workflows.
team
- 🎨 (`:art:`) for …
=> Fix swift build & release

languages/python/example.py
n/a
Update the Python binding with a state_file example.
team …
=> Update Python Binding with state_file Example

languages/csharp/Bitwarden.Sdk.Samples/Program.cs, languages/csharp/Bitwarden.Sdk/AuthClient.cs, languages/csharp/Bitwarden.Sdk/BitwardenClient.cs, languages/csharp/Bitwarden.Sdk/ProjectsClient.cs, languages/csharp/Bitwarden.Sdk/SecretsClient.cs, languages/csharp/README.md
https://bitwarden.atlassian.net/browse/SM-1400
Update the C# SDK.
team
issue and could potentially benefit from …
=> [SM-1400] Update the C# SDK

.github/workflows/release-swift.yml
https://bitwarden.atlassian.net/browse/BRE-113
Fix `release-swift.yml` workflow.
team
issue and could potentially …
=> [BRE-113] Fix release swift

Cargo.lock, crates/bitwarden-core/Cargo.toml, crates/sdk-schemas/Cargo.toml
Remove unused dependencies found by udeps.
team
- 🎨 (`:art:`) …
=> Remove unused dependencies

.vscode/settings.json, crates/bitwarden-crypto/src/aes.rs, crates/bitwarden-crypto/src/enc_string/mod.rs, crates/bitwarden-crypto/src/enc_string/symmetric.rs, crates/bitwarden-crypto/src/keys/asymmetric_crypto_key.rs, crates/bitwarden-crypto/src/keys/utils.rs, crates/bitwarden-crypto/src/lib.rs, crates/bitwarden-crypto/src/util.rs
Improve docs for crypto crate, hide private functions.
I believe only the traits in `key_encryptable` remains and @dani-garcia is planning on rewriting those which means they will be documented at that time.
team
- ❓ (`:question:`) for …
=> Improve docs for crypto crate, hide private functions

crates/bitwarden-core/src/auth/auth_request.rs, crates/bitwarden-core/src/client/encryption_settings.rs, crates/bitwarden-core/src/client/internal.rs, crates/bitwarden-core/src/error.rs, crates/bitwarden-core/src/mobile/client_crypto.rs, crates/bitwarden-core/src/mobile/crypto.rs, crates/bitwarden-uniffi/src/crypto.rs
Add an explicit error about private key being invalid.
team
- …
=> Add explicit error about invalid private key

.github/workflows/publish-python.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-289?atlOrigin=eyJpIjoiMTZmNzA5YzkyYjNjNDk4YmJhYmE0YWQ2MmQ5NzFlMzAiLCJwIjoiaiJ9)
This PR fixes the `Publish Python SDK` workflow so that it uploads to PyPi successfully.
team
- ❓ …
=> BRE-289 - Fix Publish Python SDK workflow

.github/workflows/release-swift.yml
Fix SWIFT release commit SHA and artifact upload to GitHub release.
team
issue and could potentially benefit from …
=> Fix swift release

crates/bitwarden-core/src/client/encryption_settings.rs
Temporarily disable private key validation.
team
- 🎨 …
=> Temporarily disable private key validation

.github/workflows/build-swift.yml
Add workflow_dispatch trigger to build-swift workflow.
team
- …
=> Add workflow_dispatch trigger to build-swift workflow

.github/CODEOWNERS
- [Card](https://bitwarden.atlassian.net/browse/BRE-330?atlOrigin=eyJpIjoiYmM4YWJhNDg4YjI3NDM0N2IxYmYwMTMyYmI2Y2M0N2YiLCJwIjoiaiJ9)
This PR updates the `CODEOWNERS` file so that the BRE team's automations can approve and merge PRs that change the following files:
- crates/bws/Cargo.toml
- crates/bws/scripts/install.ps1
- crates/bws/scripts/install.sh
team …
=> BRE-330 - Update CODEOWNERS for automation users

.github/workflows/build-cli-docker.yml, .github/workflows/build-rust-crates.yml, .github/workflows/publish-rust-crates.yml, .github/workflows/rust-test.yml, .github/workflows/version-bump.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-330?atlOrigin=eyJpIjoiMWE0MjNlMWUzZDI2NGQxODgyNTA3ODgxMjY5ZTAxOGEiLCJwIjoiaiJ9)
This PR updates the Rust crates workflows to release from the `main` branch instead of `rc` or `hotfix-rc`. Linting suggestions were also applied.  The `build-cli-docker.yml` workflow was updated because we no longer use the `master` branch.
- Updated any necessary documentation (Confluence, contributing docs) or informed …
=> BRE-330 - Update Rust crate workflows

.github/CODEOWNERS
- [Card](https://bitwarden.atlassian.net/browse/BRE-330?atlOrigin=eyJpIjoiMjI2MThhN2JhMDljNDg2YzkxY2M0ZTExODk4MDIwNmUiLCJwIjoiaiJ9)
This PR updates the `CODEOWNERS` file so that the Version Bump workflow can auto create PRs and merge them updating the versions for the `bws` crate.  Adding the group `@bitwarden/automation-users` did not work.
team
- 👍 …
=> BRE-330 - Update CODEOWNERS for Version Bumps

.github/workflows/publish-rust-crates.yml, Cargo.lock, crates/bitwarden/Cargo.toml, crates/bitwarden/src/error.rs, crates/bitwarden/src/lib.rs
=> Revert "[PM-12431] Temporarily un-export bitwarden_fido"

.editorconfig
`[*.{ts}]` -> `[*.ts]`
team
- 🎨 (`:art:`) for suggestions / …
=> fix: .editorconfig not being applied properly

.github/workflows/build-wasm-internal.yml, .github/workflows/build-wasm.yml, Cargo.lock, crates/bitwarden-wasm-internal/Cargo.toml, crates/bitwarden-wasm/Cargo.toml
Every time wasm-bindgen is updated we run into conflicts with the wasm-bindgen-cli version. Pin it to avoid this problem in the future.
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry …
=> Pin WASM bindgen

.github/workflows/publish-dotnet.yml, .github/workflows/publish-php.yml, .github/workflows/release-cpp.yml, .github/workflows/release-go.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-403?atlOrigin=eyJpIjoiMzMyMjIyOTgyNGJjNGYyYmJiODRjZWU3MzQ5N2M3ZWMiLCJwIjoiaiJ9)
This PR updates the CI secret name in workflows from `AZURE_CI_SERVICE_PRINCIPAL` to `AZURE_KV_CI_SERVICE_PRINCIPAL` so we don't have a duplicate repository secret.
team
- 📝 …
=> BRE-403 - Update CI Secret Name

.github/CODEOWNERS
=> Remove platform as codeowners of sdk-sm

.github/workflows/build-cli-docker.yml, .github/workflows/lint.yml, .github/workflows/scan.yml
https://bitwarden.atlassian.net/browse/VULN-226
Add correct ref/sha reference for main and PR branches, since codeql/upload-sarif doesn't handle pull_request_target properly.
team …
=> Fix SARIF upload branch ref/sha

.github/workflows/publish-bws.yml
https://bitwarden.atlassian.net/browse/BRE-826
Change docker hub to github container registry in publish bws CLI workflow.
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not …
=> [BRE-826] Update remaining DockerHub references to GitHub

.github/workflows/lint.yml
[BRE-848](https://bitwarden.atlassian.net/browse/BRE-848)
Adding permissions for uploading SARIF
team
issue and …
=> [BRE-848] Adding permissions for uploading sarif

.github/workflows/build-go.yaml, .github/workflows/test-go.yml, languages/go/bitwarden_client_test.go, languages/go/go.mod, languages/go/go.sum, languages/go/setup.sh, languages/go/test.sh, scripts/bootstrap.sh
https://bitwarden.atlassian.net/browse/SM-1512
team
- 🎨 …
=> feat: go test suite

.github/CODEOWNERS
[BRE-1040](https://bitwarden.atlassian.net/browse/BRE-1040)
Add rule to Docker-related file section of `CODEOWNERS` to include Docker Compose files.
* rule to match `docker-compose.yml`
team
- 🤔 (`:thinking:`) …
=> BRE-1040 Docker Compose rule
